//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfectAdmin
    {
        public System.DateTime Fecha { get; set; }
        public string CodAfectAdmin { get; set; }
        public string Pozo { get; set; }
        public decimal HorasPerdidas { get; set; }
        public decimal FluidoPerdido { get; set; }
        public decimal PetrPerdidoM3 { get; set; }
        public decimal PetrPerdidoTon { get; set; }
    
        public virtual CodAfectAdmin CodAfectAdmin1 { get; set; }
    }
}
