//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Usuarios
    {
        public string LoginUsuario { get; set; }
        public string DescUsuario { get; set; }
        public System.DateTime Alta { get; set; }
        public Nullable<System.DateTime> Baja { get; set; }
    }
}
