//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrosColectoresYacim
    {
        public string Mes { get; set; }
        public string Ano { get; set; }
        public string CC { get; set; }
        public decimal Qf { get; set; }
        public decimal Qp { get; set; }
        public decimal Qpton { get; set; }
        public decimal Qg { get; set; }
        public decimal PozosTrab { get; set; }
        public decimal HorasTrab { get; set; }
        public decimal HorasPlan { get; set; }
        public decimal KFluido { get; set; }
        public decimal KGas { get; set; }
        public decimal Ke { get; set; }
        public Nullable<decimal> Kaj { get; set; }
    }
}
