//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrosColectores
    {
        public System.DateTime Fecha { get; set; }
        public string CC { get; set; }
        public decimal Qf { get; set; }
        public decimal QfCalc { get; set; }
        public decimal Qg { get; set; }
        public decimal QgCalc { get; set; }
        public decimal NFinal { get; set; }
        public decimal PSep { get; set; }
        public decimal TMed { get; set; }
        public decimal PetBomb { get; set; }
        public decimal KFluido { get; set; }
        public decimal KGas { get; set; }
        public decimal Circulaciones { get; set; }
        public decimal Inyeccion { get; set; }
    }
}
