//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class cierremensualrecol
    {
        public string mes { get; set; }
        public string año { get; set; }
        public decimal numgrupo { get; set; }
        public string grupo { get; set; }
        public string nogrupo { get; set; }
        public string indicador { get; set; }
        public string um { get; set; }
        public decimal planmes { get; set; }
        public decimal realmes { get; set; }
        public decimal porcmes { get; set; }
        public decimal planaño { get; set; }
        public decimal realaño { get; set; }
        public decimal porcaño { get; set; }
        public string instalac { get; set; }
    }
}
