//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodEquipos
    {
        public string IdInstalacion { get; set; }
        public string IdEquipo { get; set; }
        public string DescEquipo { get; set; }
        public string IdTipoEquipo { get; set; }
    
        public virtual CodTipoEquipos CodTipoEquipos { get; set; }
        public virtual ParteDiarioEquipos ParteDiarioEquipos { get; set; }
    }
}
