//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodGasometros
    {
        public string IdGasom { get; set; }
        public string DescGasom { get; set; }
        public string IdPtoMedGas { get; set; }
    
        public virtual ParteDiarioGasom ParteDiarioGasom { get; set; }
    }
}
