//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodifSrv
    {
        public byte IdSrv { get; set; }
        public string DescSrv { get; set; }
        public string UM { get; set; }
        public decimal Densidad { get; set; }
    }
}
