//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodTanques
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodTanques()
        {
            this.Tanques = new HashSet<Tanques>();
            this.TanquesDinam = new HashSet<TanquesDinam>();
        }
    
        public string IdInstalacion { get; set; }
        public short Tanque { get; set; }
        public int Capacidad { get; set; }
        public int Llenado { get; set; }
        public int Piano { get; set; }
        public string IdTipoTanque { get; set; }
        public string Estado { get; set; }
        public string Contenido { get; set; }
        public string CodCUP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tanques> Tanques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TanquesDinam> TanquesDinam { get; set; }
    }
}
