//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigTrasiegosAguaI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigTrasiegosAguaI()
        {
            this.TrasiegosAguaI = new HashSet<TrasiegosAguaI>();
        }
    
        public short IdTrasiego { get; set; }
        public string IdOrigen { get; set; }
        public string IdDestino { get; set; }
        public byte IdTipo { get; set; }
    
        public virtual TiposTrasiego TiposTrasiego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrasiegosAguaI> TrasiegosAguaI { get; set; }
    }
}
