//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumoGasoil
    {
        public string fecha { get; set; }
        public string unidad { get; set; }
        public decimal entrada { get; set; }
        public decimal consumo { get; set; }
    }
}
