//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosFlareYacim
    {
        public System.DateTime Fecha { get; set; }
        public byte IdFlareYacim { get; set; }
        public decimal GasFlereado { get; set; }
    
        public virtual CodFlareYacim CodFlareYacim { get; set; }
    }
}
