//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosbuqueterm
    {
        public string fecha { get; set; }
        public string buque { get; set; }
        public string destino { get; set; }
        public decimal ventam3 { get; set; }
        public decimal ventaton { get; set; }
        public decimal bswcent { get; set; }
        public decimal bswdest { get; set; }
        public decimal temp { get; set; }
        public decimal api { get; set; }
        public decimal porcazufre { get; set; }
        public decimal densidad { get; set; }
        public decimal precio { get; set; }
        public decimal importe { get; set; }
        public decimal lastre { get; set; }
        public decimal viscosidad { get; set; }
        public decimal sales { get; set; }
        public string fatraque { get; set; }
        public decimal hatraque { get; set; }
        public string fcomienzo { get; set; }
        public decimal hcomienzo { get; set; }
        public string fterminac { get; set; }
        public decimal hterminac { get; set; }
    }
}
