//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosValvulasCorte
    {
        public string fecha { get; set; }
        public string valvula { get; set; }
        public decimal temp { get; set; }
        public decimal presion { get; set; }
        public decimal voltaje { get; set; }
    }
}
