//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class desgsrv
    {
        public string fecha { get; set; }
        public string codptosum { get; set; }
        public string codsrv { get; set; }
        public decimal mr { get; set; }
        public decimal mb { get; set; }
        public decimal exist { get; set; }
        public decimal diesel { get; set; }
        public decimal dosif { get; set; }
    }
}
