//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class desgafectgasom
    {
        public string fecha { get; set; }
        public string ptomed { get; set; }
        public string codgasom { get; set; }
        public string codafect { get; set; }
        public decimal hp { get; set; }
    }
}
