//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class desgafectpozos
    {
        public string fecha { get; set; }
        public string codigo { get; set; }
        public string pozo { get; set; }
        public decimal hp { get; set; }
        public decimal prodperdida { get; set; }
        public decimal prodperdton { get; set; }
        public decimal prodperdm3 { get; set; }
    }
}
