//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class desgestrebomb
    {
        public string fecha { get; set; }
        public string coder { get; set; }
        public decimal petbombm3 { get; set; }
        public decimal petbombt { get; set; }
        public decimal nfinal { get; set; }
    }
}
