//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class desgcentroscolectores
    {
        public string fecha { get; set; }
        public string cc { get; set; }
        public decimal qf { get; set; }
        public decimal qfcalc { get; set; }
        public decimal qg { get; set; }
        public decimal qgcalc { get; set; }
        public decimal nfinal { get; set; }
        public decimal psep { get; set; }
        public decimal tmed { get; set; }
        public decimal petbomb { get; set; }
        public decimal kfluido { get; set; }
        public decimal kgas { get; set; }
        public decimal circulacio { get; set; }
        public decimal inyeccion { get; set; }
    }
}
