//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class existf
    {
        public string año { get; set; }
        public string mes { get; set; }
        public string codigo { get; set; }
        public string instalac { get; set; }
        public decimal exist { get; set; }
    }
}
