//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class FondoPozosYacim
    {
        public string Mes { get; set; }
        public string Ano { get; set; }
        public string Pozo { get; set; }
        public string Categoria { get; set; }
        public string Propietario { get; set; }
        public string Operador { get; set; }
        public string ProdFund { get; set; }
        public string TipoPozo { get; set; }
        public string Metodo { get; set; }
        public string Regimen { get; set; }
        public string EntGas { get; set; }
        public string EntPet { get; set; }
        public string TipoMedGas { get; set; }
        public string TipoPet { get; set; }
        public string Ciclo { get; set; }
        public string PozoViejo { get; set; }
        public string CColector { get; set; }
        public string CMed { get; set; }
    }
}
