//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class histafectpozos
    {
        public string mes { get; set; }
        public string ano { get; set; }
        public string pozo { get; set; }
        public string codafect { get; set; }
        public decimal hp { get; set; }
        public decimal hpfa { get; set; }
        public decimal prodperdid { get; set; }
        public decimal prodkeperd { get; set; }
    }
}
