//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class histafectgasom
    {
        public string mes { get; set; }
        public string ano { get; set; }
        public string ptomed { get; set; }
        public string gasom { get; set; }
        public string afect { get; set; }
        public decimal hp { get; set; }
    }
}
