//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class histcentroscolectores
    {
        public string mes { get; set; }
        public string ano { get; set; }
        public string cc { get; set; }
        public decimal qf { get; set; }
        public decimal qp { get; set; }
        public decimal qg { get; set; }
        public decimal pozostrab { get; set; }
        public decimal horastrab { get; set; }
        public decimal horasplan { get; set; }
        public decimal kfluido { get; set; }
        public decimal kgas { get; set; }
        public decimal ke { get; set; }
    }
}
