//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class histproddia
    {
        public string fecha { get; set; }
        public decimal prodbatd { get; set; }
        public decimal prodbatm { get; set; }
        public decimal prodbata { get; set; }
        public decimal vcampod { get; set; }
        public decimal vcampom { get; set; }
        public decimal vcampoa { get; set; }
        public decimal entgasd { get; set; }
        public decimal entgasm { get; set; }
        public decimal entgasa { get; set; }
        public decimal metrd { get; set; }
        public decimal metrm { get; set; }
        public decimal metra { get; set; }
        public decimal prodcd { get; set; }
        public decimal prodcm { get; set; }
        public decimal prodca { get; set; }
        public decimal fluidcampo { get; set; }
        public decimal trascampo { get; set; }
        public decimal pozactd { get; set; }
        public decimal pozactm { get; set; }
        public decimal pozinad { get; set; }
        public decimal pozinam { get; set; }
        public decimal horastrab { get; set; }
        public decimal horastrabm { get; set; }
        public decimal horasafec { get; set; }
        public decimal horasafecm { get; set; }
        public decimal ke { get; set; }
        public decimal kem { get; set; }
        public decimal ku { get; set; }
        public decimal kum { get; set; }
        public decimal pronostico { get; set; }
    }
}
