//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicCalidad_Usuarios
    {
        public string LoginUsuario { get; set; }
        public string DescUsuario { get; set; }
        public bool Nivel1 { get; set; }
        public bool Nivel2 { get; set; }
        public bool Nivel3 { get; set; }
        public bool Nivel4 { get; set; }
    }
}
