//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicCalidad
    {
        public byte Indic_id { get; set; }
        public string Indic_desc { get; set; }
        public string Um { get; set; }
        public string Tipo { get; set; }
    }
}
