//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumosRecol
    {
        public System.DateTime Fecha { get; set; }
        public string IdInstalacion { get; set; }
        public string IdProducto { get; set; }
        public decimal Entrada { get; set; }
        public decimal Consumo { get; set; }
    
        public virtual CodInstalaciones CodInstalaciones { get; set; }
        public virtual CodProductos CodProductos { get; set; }
    }
}
