//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventarios
    {
        public string IdInstalacion { get; set; }
        public short IdTanque { get; set; }
        public decimal Existm3 { get; set; }
        public decimal Temp { get; set; }
        public decimal Bsw { get; set; }
        public decimal Viscosidad { get; set; }
        public decimal Api { get; set; }
    }
}
