//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class InyeccFluidos
    {
        public string Pozo_Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte Fluido_Id { get; set; }
        public decimal TMed_Iny { get; set; }
        public decimal Qf_Iny { get; set; }
        public decimal Pres_Iny { get; set; }
        public decimal Temp_Iny { get; set; }
        public byte Inyector_Id { get; set; }
    
        public virtual FluidosIny FluidosIny { get; set; }
        public virtual Inyectores Inyectores { get; set; }
    }
}
