//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParamTHD
    {
        public string IdInstalacion { get; set; }
        public short IdTanque { get; set; }
        public decimal ColAgua { get; set; }
        public decimal TempColAgua { get; set; }
        public decimal TempEnt { get; set; }
        public decimal TempSal { get; set; }
        public decimal BswEnt { get; set; }
        public decimal BswSal { get; set; }
        public decimal ViscEnt { get; set; }
        public decimal ViscSal { get; set; }
    
        public virtual CodInstalaciones CodInstalaciones { get; set; }
    }
}
