//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipContratos
    {
        public byte IdContrato { get; set; }
        public decimal RecupGastos { get; set; }
        public decimal GananciaCupet { get; set; }
        public decimal GananciaCia { get; set; }
        public System.DateTime FechaIni { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        public virtual ContratosCias ContratosCias { get; set; }
    }
}
