//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteDiario_Majagua
    {
        public System.DateTime Fecha { get; set; }
        public decimal ProdPetrTonT { get; set; }
        public decimal ProdPetrTonN { get; set; }
        public decimal EntGasm3 { get; set; }
        public decimal VentasPetrTon { get; set; }
    }
}
