//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParteDiarioPozos
    {
        public string Pozo { get; set; }
        public decimal Qf { get; set; }
        public decimal Tt { get; set; }
        public decimal Pt { get; set; }
        public decimal Pc { get; set; }
        public decimal Qg { get; set; }
        public string Afect { get; set; }
        public decimal TMed { get; set; }
        public decimal PSep { get; set; }
        public decimal NFinal { get; set; }
        public decimal Tras { get; set; }
        public string Observ { get; set; }
        public string VAsf { get; set; }
        public string VGas { get; set; }
    }
}
