//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class PozosA
    {
        public string Pozo { get; set; }
        public int DiasAct { get; set; }
        public int DiasIna { get; set; }
        public decimal Tt { get; set; }
        public decimal HPlan { get; set; }
    }
}
