//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdPozos
    {
        public System.DateTime Fecha { get; set; }
        public string Pozo { get; set; }
        public string Operador { get; set; }
        public string CColector { get; set; }
        public byte Conectado { get; set; }
        public decimal HPlan { get; set; }
        public string Ciclo { get; set; }
        public decimal Qf { get; set; }
        public decimal Tt { get; set; }
        public decimal TtProd { get; set; }
        public decimal Qg { get; set; }
        public decimal Bsw { get; set; }
        public decimal Rgp { get; set; }
        public decimal Pbase { get; set; }
        public decimal Circulacion { get; set; }
        public decimal Paga { get; set; }
        public decimal Debe { get; set; }
        public decimal NFinal { get; set; }
        public short Tras { get; set; }
        public decimal Pt { get; set; }
        public decimal Pc { get; set; }
        public string Observ { get; set; }
        public string CMed { get; set; }
    }
}
