//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodmens
    {
        public string año { get; set; }
        public string mes { get; set; }
        public string instalac { get; set; }
        public decimal existin { get; set; }
        public decimal liqrec { get; set; }
        public decimal pettrat { get; set; }
        public decimal petrecp { get; set; }
        public decimal pettratce { get; set; }
        public decimal petcal { get; set; }
        public decimal petscal { get; set; }
        public decimal bombpi { get; set; }
        public decimal aguavpi { get; set; }
        public decimal petrecup { get; set; }
        public decimal existfin { get; set; }
        public decimal bswent { get; set; }
        public decimal aguad { get; set; }
        public decimal prodpet { get; set; }
        public decimal entbcacc { get; set; }
        public decimal entbcasc { get; set; }
        public decimal venta { get; set; }
        public decimal bswp { get; set; }
        public decimal ventam2 { get; set; }
        public decimal entoleo { get; set; }
        public decimal bomc3 { get; set; }
        public decimal bomc4 { get; set; }
        public decimal pbcebca { get; set; }
        public decimal csal { get; set; }
        public decimal cformula { get; set; }
        public decimal cform680 { get; set; }
        public decimal petcald { get; set; }
        public decimal conelect { get; set; }
        public decimal congasoil { get; set; }
        public decimal convapor { get; set; }
        public decimal aguac { get; set; }
        public decimal aguat { get; set; }
        public decimal indcele { get; set; }
        public decimal indcsal { get; set; }
        public decimal indcfor { get; set; }
        public decimal indcvapor { get; set; }
        public decimal inyecpoz { get; set; }
        public decimal lastre { get; set; }
        public decimal varacal { get; set; }
        public decimal btranmant { get; set; }
        public string codmant { get; set; }
        public decimal btranmact { get; set; }
    }
}
