//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdBase
    {
        public string Pozo { get; set; }
        public decimal ene { get; set; }
        public decimal feb { get; set; }
        public decimal mar { get; set; }
        public decimal abr { get; set; }
        public decimal may { get; set; }
        public decimal jun { get; set; }
        public decimal jul { get; set; }
        public decimal ago { get; set; }
        public decimal sep { get; set; }
        public decimal oct { get; set; }
        public decimal nov { get; set; }
        public decimal dic { get; set; }
        public short anno { get; set; }
        public decimal merma { get; set; }
    }
}
