//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdPozosCierre
    {
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public string Pozo { get; set; }
        public string CColector { get; set; }
        public byte Conectado { get; set; }
        public string ProdFund { get; set; }
        public string Operador { get; set; }
        public decimal Qpm3 { get; set; }
        public decimal Densidad { get; set; }
        public decimal API { get; set; }
        public decimal HorasTrab { get; set; }
        public decimal HorasPlan { get; set; }
        public decimal KFluido { get; set; }
    }
}
