//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class PtoInyParam
    {
        public System.DateTime Fecha { get; set; }
        public string IdInstalacion { get; set; }
        public decimal AguaIny { get; set; }
        public decimal HorasIny { get; set; }
        public decimal TempIny { get; set; }
        public decimal PresIny { get; set; }
    }
}
