//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados
    {
        public System.DateTime Fecha { get; set; }
        public string IdInstalacion { get; set; }
        public decimal ExistM3 { get; set; }
        public decimal ExistTon { get; set; }
        public decimal TrasiegoPailaM3 { get; set; }
        public decimal TrasiegoPailaTon { get; set; }
        public decimal TrasiegoOleoductoM3 { get; set; }
        public decimal TrasiegoOleoductoTon { get; set; }
        public decimal FluidoEntradaM3 { get; set; }
        public decimal FluidoEntradaTon { get; set; }
        public decimal ProdM3 { get; set; }
        public decimal ProdTon { get; set; }
        public decimal TonPailas { get; set; }
        public decimal PetCalidad { get; set; }
        public decimal CapacOperacional { get; set; }
        public decimal AguaDrenM3 { get; set; }
        public decimal AguaDrenTon { get; set; }
        public decimal ProdTeoricaTon { get; set; }
        public decimal FondoExtraM3 { get; set; }
        public decimal FondoExtraTon { get; set; }
        public decimal FondoAgregM3 { get; set; }
        public decimal FondoAgregTon { get; set; }
        public decimal PetRecupM3 { get; set; }
        public decimal PetRecupTon { get; set; }
    }
}
