//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Srv
    {
        public System.DateTime Fecha { get; set; }
        public string IdPtoSum { get; set; }
        public string IdSrv { get; set; }
        public decimal Mr { get; set; }
        public decimal Mb { get; set; }
        public decimal Exist { get; set; }
        public decimal PorcSust { get; set; }
        public decimal Dosif { get; set; }
        public int mio { get; set; }
    
        public virtual CodSrv CodSrv { get; set; }
    }
}
