//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Srv_Diario
    {
        public System.DateTime Fecha { get; set; }
        public string IdPtoSum { get; set; }
        public byte IdSrv { get; set; }
        public decimal SustBomb { get; set; }
        public decimal FluidoBomb { get; set; }
    }
}
