//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class submayorcald
    {
        public decimal caldera { get; set; }
        public decimal acumhort { get; set; }
        public decimal acumhorta { get; set; }
        public decimal hormant { get; set; }
        public decimal horafmant { get; set; }
    }
}
