//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanques
    {
        public System.DateTime Fecha { get; set; }
        public string IdInstalacion { get; set; }
        public short IdTanque { get; set; }
        public decimal Existm3 { get; set; }
        public decimal Existton { get; set; }
        public decimal Bsw { get; set; }
        public decimal Temp { get; set; }
        public decimal Api { get; set; }
        public decimal AguaDrenm3 { get; set; }
        public decimal AguaDrenton { get; set; }
        public decimal Ventasm3 { get; set; }
        public decimal Ventaston { get; set; }
        public decimal PetRecupm3 { get; set; }
        public decimal PetRecupton { get; set; }
        public decimal FondoExtram3 { get; set; }
        public decimal FondoExtraton { get; set; }
        public decimal FondoAgregm3 { get; set; }
        public decimal FondoAgregton { get; set; }
    
        public virtual CodTanques CodTanques { get; set; }
    }
}
