//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGasGasod
    {
        public System.DateTime Fecha { get; set; }
        public string IdGasod { get; set; }
        public string CodDestino { get; set; }
        public decimal Ventam3 { get; set; }
        public decimal VentaCalcm3 { get; set; }
        public bool Flare { get; set; }
        public bool ProblTecn { get; set; }
        public Nullable<decimal> CoefAj { get; set; }
        public bool Certificada { get; set; }
        public bool FueraServicio { get; set; }
    
        public virtual CodDestinos CodDestinos { get; set; }
    }
}
