//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sisprod
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPetPailas
    {
        public System.DateTime Fecha { get; set; }
        public string IdInstalacion { get; set; }
        public string IdPaila { get; set; }
        public string Conduce { get; set; }
        public string CodDestino { get; set; }
        public decimal Ventam3 { get; set; }
        public decimal Ventaton { get; set; }
        public decimal Bsw { get; set; }
        public decimal Api { get; set; }
        public decimal Densidad { get; set; }
    
        public virtual CodDestinos CodDestinos { get; set; }
        public virtual CodInstalaciones CodInstalaciones { get; set; }
        public virtual CodPailas CodPailas { get; set; }
    }
}
