//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtrasarMttoMotor
    {
        public string motor_NumSerie { get; set; }
        public float amm_Litros { get; set; }
        public string Login { get; set; }
        public System.DateTime amm_Fecha { get; set; }
    
        public virtual Motores Motores { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
