//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class BajasMotores
    {
        public string motor_NumSerie { get; set; }
        public System.DateTime bmotor_FechaBaja { get; set; }
        public string bmotor_MotivoBaja { get; set; }
        public string bmotor_Observ { get; set; }
    
        public virtual Motores Motores { get; set; }
    }
}
