//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class BajasNeumaticos
    {
        public string neum_PC { get; set; }
        public System.DateTime bneum_FechaBaja { get; set; }
        public short nmb_Id { get; set; }
        public string bneum_Observ { get; set; }
    
        public virtual Neumaticos Neumaticos { get; set; }
        public virtual NeumMotivoBaja NeumMotivoBaja { get; set; }
    }
}
