//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA
    {
        public long ID { get; set; }
        public System.DateTime FECHAHORA { get; set; }
        public string HOST { get; set; }
        public string USERNAME { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
