//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentrosCostos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentrosCostos()
        {
            this.ConsCombMotBT = new HashSet<ConsCombMotBT>();
            this.ConsumoCombustibleMotores = new HashSet<ConsumoCombustibleMotores>();
            this.DistBonosCombEq = new HashSet<DistBonosCombEq>();
            this.DistImporteBonosCC = new HashSet<DistImporteBonosCC>();
            this.Equipos = new HashSet<Equipos>();
            this.SubmayorBonosPeaje = new HashSet<SubmayorBonosPeaje>();
            this.mundo_Talleres = new HashSet<mundo_Talleres>();
            this.OrdenesTrabajo = new HashSet<OrdenesTrabajo>();
            this.OTServiciosPrestados = new HashSet<OTServiciosPrestados>();
            this.OTServiciosPrestados1 = new HashSet<OTServiciosPrestados>();
            this.Salidas_Almacenes = new HashSet<Salidas_Almacenes>();
            this.SubmayorPeaje = new HashSet<SubmayorPeaje>();
            this.SubmayorTarjetasExternas = new HashSet<SubmayorTarjetasExternas>();
            this.TarjetasExternas = new HashSet<TarjetasExternas>();
            this.TarjetasPeaje = new HashSet<TarjetasPeaje>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int ccosto_id { get; set; }
        public string ccosto_codcencos { get; set; }
        public string ccosto_descrip { get; set; }
        public bool ccosto_Inactivo { get; set; }
        public Nullable<short> dir_ID { get; set; }
        public bool ExportDataExcluir { get; set; }
        public bool xmlContaExcluir { get; set; }
    
        public virtual Direcciones Direcciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsCombMotBT> ConsCombMotBT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumoCombustibleMotores> ConsumoCombustibleMotores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistBonosCombEq> DistBonosCombEq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistImporteBonosCC> DistImporteBonosCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipos> Equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmayorBonosPeaje> SubmayorBonosPeaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mundo_Talleres> mundo_Talleres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesTrabajo> OrdenesTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTServiciosPrestados> OTServiciosPrestados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTServiciosPrestados> OTServiciosPrestados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salidas_Almacenes> Salidas_Almacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmayorPeaje> SubmayorPeaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmayorTarjetasExternas> SubmayorTarjetasExternas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarjetasExternas> TarjetasExternas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarjetasPeaje> TarjetasPeaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
