//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesCiclosMantenimiento
    {
        public byte mciclo_Id { get; set; }
        public string mmant_Id { get; set; }
        public short dcm_NoDeOrden { get; set; }
    
        public virtual mundo_CiclosMantenimiento mundo_CiclosMantenimiento { get; set; }
        public virtual mundo_Mantenimientos mundo_Mantenimientos { get; set; }
    }
}
