//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOT_ManoObra
    {
        public long ot_Id { get; set; }
        public System.DateTime dotmo_Fecha { get; set; }
        public short mo_Id { get; set; }
        public short dotmo_Horas { get; set; }
        public byte dotmo_Min { get; set; }
        public decimal dotmo_Tarifa { get; set; }
        public byte mBrig_id { get; set; }
        public bool dotmo_Incluye30RC { get; set; }
        public decimal dotmo_PctoGI { get; set; }
        public string OperacionesRealizadas { get; set; }
    
        public virtual mundo_Brigadas mundo_Brigadas { get; set; }
    }
}
