//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetOT_TiempoReparacion
    {
        public long ot_Id { get; set; }
        public System.DateTime dottr_Fecha { get; set; }
        public short dottr_Horas { get; set; }
        public byte dottr_Min { get; set; }
    }
}
