//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOTT_ManoObra
    {
        public long ott_Id { get; set; }
        public System.DateTime dottmo_Fecha { get; set; }
        public short mo_Id { get; set; }
        public short dottmo_Horas { get; set; }
        public byte dottmo_Min { get; set; }
        public decimal dottmo_Tarifa { get; set; }
        public byte mBrig_id { get; set; }
        public bool dottmo_Incluye30RC { get; set; }
        public decimal dottmo_PctoGI { get; set; }
        public string OperacionesRealizadas { get; set; }
    }
}
