//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entidades()
        {
            this.LugarCarga = new HashSet<LugarCarga>();
            this.LugarDescarga = new HashSet<LugarDescarga>();
            this.OT_Terceros = new HashSet<OT_Terceros>();
            this.OTServiciosPrestados = new HashSet<OTServiciosPrestados>();
        }
    
        public short ent_Id { get; set; }
        public string ent_Nombre { get; set; }
        public string ent_Direccion { get; set; }
        public string ent_CtaBancaria { get; set; }
        public string ent_Email { get; set; }
        public string ent_Telefono { get; set; }
        public bool NoActivo { get; set; }
        public bool Interno { get; set; }
        public string Cod_DPA { get; set; }
        public string CodREUP { get; set; }
        public short CantTrabTransportar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LugarCarga> LugarCarga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LugarDescarga> LugarDescarga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT_Terceros> OT_Terceros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTServiciosPrestados> OTServiciosPrestados { get; set; }
    }
}
