//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiposServicios
    {
        public string eq_NumOperacional { get; set; }
        public byte ServiciosID { get; set; }
        public decimal TarifaKmsVacio { get; set; }
        public decimal TarifaHrsMora { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual mundo_Servicios mundo_Servicios { get; set; }
    }
}
