//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExistProd_Taller
    {
        public long ept_Id { get; set; }
        public string ept_CodProd { get; set; }
        public string ept_Desc { get; set; }
        public string ept_UM { get; set; }
        public decimal ept_Precio { get; set; }
        public decimal ept_PrecioCUC { get; set; }
        public decimal ept_Existencia { get; set; }
        public string ept_PiezasAccMat { get; set; }
        public string ept_ElemCUC { get; set; }
        public string ept_ElemMN { get; set; }
    }
}
