//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class HojaRuta
    {
        public int HR_ID { get; set; }
        public byte Trafico_ID { get; set; }
        public string hr_NoHR { get; set; }
        public string eq_NumOperacional { get; set; }
        public int mthr_id { get; set; }
        public string hr_NumOpArrastre { get; set; }
        public string hr_NumOpArrastre2 { get; set; }
        public string hr_Observ { get; set; }
        public string Login { get; set; }
        public string hr_Estado { get; set; }
        public Nullable<short> c_Id { get; set; }
        public decimal hr_KmsGPS { get; set; }
        public Nullable<int> Ayudante_ID { get; set; }
    
        public virtual Ayudantes Ayudantes { get; set; }
        public virtual Choferes Choferes { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual Equipos Equipos1 { get; set; }
        public virtual Equipos Equipos2 { get; set; }
        public virtual mundo_TipoHR mundo_TipoHR { get; set; }
        public virtual mundo_Trafico mundo_Trafico { get; set; }
    }
}
