//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class LugarDescarga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LugarDescarga()
        {
            this.ConsCombMotBT = new HashSet<ConsCombMotBT>();
            this.SubmayorTarjetasExternas = new HashSet<SubmayorTarjetasExternas>();
        }
    
        public int ldesc_ID { get; set; }
        public string ldesc_Nombre { get; set; }
        public short ent_Id { get; set; }
        public bool ldesc_Inactivo { get; set; }
        public string Cod_DPA { get; set; }
        public string Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsCombMotBT> ConsCombMotBT { get; set; }
        public virtual Entidades Entidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmayorTarjetasExternas> SubmayorTarjetasExternas { get; set; }
    }
}
