//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimientos
    {
        public int mant_id { get; set; }
        public byte mtaller_id { get; set; }
        public string motor_NumSerie { get; set; }
        public System.DateTime mant_Fecha { get; set; }
        public string mmant_Id { get; set; }
        public string eq_NumOperacional { get; set; }
        public Nullable<float> mant_LitrosParciales { get; set; }
        public Nullable<float> mant_Litros { get; set; }
        public string mant_Tipo { get; set; }
        public short mant_NoOT { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Motores Motores { get; set; }
        public virtual mundo_Mantenimientos mundo_Mantenimientos { get; set; }
    }
}
