//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motores()
        {
            this.AsignacionesMotores = new HashSet<AsignacionesMotores>();
            this.ConsCombMotBT = new HashSet<ConsCombMotBT>();
            this.ConsumoCombustibleMotores = new HashSet<ConsumoCombustibleMotores>();
            this.Mantenimientos = new HashSet<Mantenimientos>();
            this.MotoresComb = new HashSet<MotoresComb>();
            this.MotoresNormasConsumo = new HashSet<MotoresNormasConsumo>();
        }
    
        public short mmotor_id { get; set; }
        public string motor_NumSerie { get; set; }
        public System.DateTime motor_FechaAlta { get; set; }
        public float motor_Litros { get; set; }
        public float motor_LitrosAlta { get; set; }
        public float motor_LitrosParciales { get; set; }
        public string motor_TipoAlta { get; set; }
        public decimal dcm_NoDeOrden { get; set; }
        public string motor_Tipo { get; set; }
        public decimal motor_Norma { get; set; }
        public decimal motor_NormaHoras { get; set; }
    
        public virtual AdelantarMttoMotor AdelantarMttoMotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionesMotores> AsignacionesMotores { get; set; }
        public virtual AtrasarMttoMotor AtrasarMttoMotor { get; set; }
        public virtual BajasMotores BajasMotores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsCombMotBT> ConsCombMotBT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumoCombustibleMotores> ConsumoCombustibleMotores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimientos> Mantenimientos { get; set; }
        public virtual mundo_motores mundo_motores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotoresComb> MotoresComb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotoresNormasConsumo> MotoresNormasConsumo { get; set; }
        public virtual Equipos Equipos { get; set; }
    }
}
