//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class MttoFuera_RotSistemas
    {
        public int MFID { get; set; }
        public byte msa_Id { get; set; }
        public System.DateTime mfrot_Fecha { get; set; }
        public short mfrot_Cantidad { get; set; }
    }
}
