//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class mundo_Paises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mundo_Paises()
        {
            this.mundo_MarcasBateria = new HashSet<mundo_MarcasBateria>();
            this.mundo_MarcasEquipos = new HashSet<mundo_MarcasEquipos>();
            this.mundo_MarcasMotores = new HashSet<mundo_MarcasMotores>();
            this.mundo_MarcasNeumaticos = new HashSet<mundo_MarcasNeumaticos>();
        }
    
        public short mp_Id { get; set; }
        public string mp_Pais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mundo_MarcasBateria> mundo_MarcasBateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mundo_MarcasEquipos> mundo_MarcasEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mundo_MarcasMotores> mundo_MarcasMotores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mundo_MarcasNeumaticos> mundo_MarcasNeumaticos { get; set; }
    }
}
