//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class mundo_Aceites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mundo_Aceites()
        {
            this.mundo_motores = new HashSet<mundo_motores>();
        }
    
        public int mac_Id { get; set; }
        public string mac_Desc { get; set; }
        public string mac_Tipo { get; set; }
        public float mac_Precio { get; set; }
        public bool mac_Excluido { get; set; }
        public string codprodalm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mundo_motores> mundo_motores { get; set; }
    }
}
