//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class mundo_RotSistemas
    {
        public short mrs_Id { get; set; }
        public byte msa_Id { get; set; }
        public string mrs_Desc { get; set; }
    
        public virtual mundo_SistemasAuto mundo_SistemasAuto { get; set; }
    }
}
