//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class mundo_MarcasEquipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mundo_MarcasEquipos()
        {
            this.mundo_Equipos = new HashSet<mundo_Equipos>();
        }
    
        public short mmeq_Id { get; set; }
        public short mp_Id { get; set; }
        public string mmeq_Marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mundo_Equipos> mundo_Equipos { get; set; }
        public virtual mundo_Paises mundo_Paises { get; set; }
    }
}
