//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class mundo_Baterias
    {
        public short mbat_Id { get; set; }
        public short mmbat_Id { get; set; }
        public byte mbat_Voltaje { get; set; }
        public float mbat_Amperaje { get; set; }
        public float mbat_Norma { get; set; }
    
        public virtual mundo_MarcasBateria mundo_MarcasBateria { get; set; }
    }
}
