//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class mundo_Equipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mundo_Equipos()
        {
            this.Equipos = new HashSet<Equipos>();
        }
    
        public short meq_Id { get; set; }
        public string mce_Id { get; set; }
        public short mmeq_Id { get; set; }
        public string meq_Desc { get; set; }
        public string meq_Modelo { get; set; }
        public float meq_Capacidad { get; set; }
        public float meq_Tara { get; set; }
        public float meq_Impuesto { get; set; }
        public byte meq_MinBat { get; set; }
        public byte meq_MinNeum { get; set; }
        public byte meq_MaxBat { get; set; }
        public byte meq_MaxNeum { get; set; }
        public byte meq_MinMotor { get; set; }
        public byte meq_MaxMotor { get; set; }
        public byte meq_NoPlazas { get; set; }
        public byte meq_NoEjes { get; set; }
        public byte meq_NoPuertas { get; set; }
        public byte mcar_Id { get; set; }
        public byte mcab_Id { get; set; }
        public byte mt_Id { get; set; }
        public byte mtrans_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipos> Equipos { get; set; }
        public virtual mundo_Cabinas mundo_Cabinas { get; set; }
        public virtual mundo_Carrocerias mundo_Carrocerias { get; set; }
        public virtual mundo_CategoriasEquipos mundo_CategoriasEquipos { get; set; }
        public virtual mundo_MarcasEquipos mundo_MarcasEquipos { get; set; }
        public virtual mundo_Traccion mundo_Traccion { get; set; }
        public virtual mundo_Transmision mundo_Transmision { get; set; }
    }
}
