//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class mundo_Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mundo_Servicios()
        {
            this.EquiposServicios = new HashSet<EquiposServicios>();
            this.OTServPrestDet = new HashSet<OTServPrestDet>();
        }
    
        public byte ServiciosID { get; set; }
        public string ServiciosDesc { get; set; }
        public string ServUM { get; set; }
        public decimal TarifaMNClientes { get; set; }
        public decimal TarifaMLCClientes { get; set; }
        public decimal TarifaMNCCostos { get; set; }
        public decimal TarifaMLCCCostos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquiposServicios> EquiposServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTServPrestDet> OTServPrestDet { get; set; }
    }
}
