//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neumaticos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Neumaticos()
        {
            this.AsignacionesNeumaticos = new HashSet<AsignacionesNeumaticos>();
            this.NeumRepEq = new HashSet<NeumRepEq>();
            this.KmsNeumaticos = new HashSet<KmsNeumaticos>();
            this.Equipos = new HashSet<Equipos>();
        }
    
        public short mneum_Id { get; set; }
        public string neum_PC { get; set; }
        public System.DateTime neum_FechaAlta { get; set; }
        public float neum_Kms { get; set; }
        public string neum_TipoAlta { get; set; }
        public float neum_KmsAlta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionesNeumaticos> AsignacionesNeumaticos { get; set; }
        public virtual BajasNeumaticos BajasNeumaticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NeumRepEq> NeumRepEq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KmsNeumaticos> KmsNeumaticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipos> Equipos { get; set; }
    }
}
