//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanesMesIndicEq
    {
        public string eq_NumOperacional { get; set; }
        public short Año { get; set; }
        public byte Mes { get; set; }
        public byte i_Id { get; set; }
        public decimal Cantidad { get; set; }
        public string mcomb_Id { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual mundo_Combustibles mundo_Combustibles { get; set; }
        public virtual mundo_Indicadores mundo_Indicadores { get; set; }
    }
}
