//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecaudaOmnibus
    {
        public string eq_NumOperacional { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public Nullable<short> c_Id { get; set; }
        public decimal Importe { get; set; }
    
        public virtual Choferes Choferes { get; set; }
        public virtual Equipos Equipos { get; set; }
    }
}
