//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SitransEntities : DbContext
    {
        public SitransEntities()
            : base("name=SitransEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<AccidenteTipo> AccidenteTipo { get; set; }
        public virtual DbSet<AdelantarMttoMotor> AdelantarMttoMotor { get; set; }
        public virtual DbSet<AsignacionesArrastres> AsignacionesArrastres { get; set; }
        public virtual DbSet<AsignacionesBaterias> AsignacionesBaterias { get; set; }
        public virtual DbSet<AsignacionesMotores> AsignacionesMotores { get; set; }
        public virtual DbSet<AsignacionesNeumaticos> AsignacionesNeumaticos { get; set; }
        public virtual DbSet<AtrasarMttoMotor> AtrasarMttoMotor { get; set; }
        public virtual DbSet<Ayudantes> Ayudantes { get; set; }
        public virtual DbSet<BajasBaterias> BajasBaterias { get; set; }
        public virtual DbSet<BajasEquipos> BajasEquipos { get; set; }
        public virtual DbSet<BajasMotores> BajasMotores { get; set; }
        public virtual DbSet<BajasNeumaticos> BajasNeumaticos { get; set; }
        public virtual DbSet<Baterias> Baterias { get; set; }
        public virtual DbSet<BatMotivoBaja> BatMotivoBaja { get; set; }
        public virtual DbSet<BITACORA> BITACORA { get; set; }
        public virtual DbSet<CartaTecnEqMttoOT> CartaTecnEqMttoOT { get; set; }
        public virtual DbSet<CentrosCostos> CentrosCostos { get; set; }
        public virtual DbSet<Choferes> Choferes { get; set; }
        public virtual DbSet<cnConfGestorAlm> cnConfGestorAlm { get; set; }
        public virtual DbSet<ConsCombMotBT> ConsCombMotBT { get; set; }
        public virtual DbSet<ConsumoCombustibleMotores> ConsumoCombustibleMotores { get; set; }
        public virtual DbSet<ControlDocEquipos> ControlDocEquipos { get; set; }
        public virtual DbSet<DetallesCiclosMantenimiento> DetallesCiclosMantenimiento { get; set; }
        public virtual DbSet<DetallesHojaRuta> DetallesHojaRuta { get; set; }
        public virtual DbSet<DetOT_ManoObra> DetOT_ManoObra { get; set; }
        public virtual DbSet<DetOT_Materiales> DetOT_Materiales { get; set; }
        public virtual DbSet<DetOT_RotSistemas> DetOT_RotSistemas { get; set; }
        public virtual DbSet<DetOT_TiempoInactivo> DetOT_TiempoInactivo { get; set; }
        public virtual DbSet<DetSalAlm> DetSalAlm { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<DistBonosCombEq> DistBonosCombEq { get; set; }
        public virtual DbSet<DistImporteBonosCC> DistImporteBonosCC { get; set; }
        public virtual DbSet<DistribTarjSolicitudCargue> DistribTarjSolicitudCargue { get; set; }
        public virtual DbSet<DOTT_ManoObra> DOTT_ManoObra { get; set; }
        public virtual DbSet<DOTT_Materiales> DOTT_Materiales { get; set; }
        public virtual DbSet<DPA> DPA { get; set; }
        public virtual DbSet<Entidades> Entidades { get; set; }
        public virtual DbSet<EntSalParqueoEmpresa> EntSalParqueoEmpresa { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<EquiposAccidentes> EquiposAccidentes { get; set; }
        public virtual DbSet<EquiposServicios> EquiposServicios { get; set; }
        public virtual DbSet<HojaRuta> HojaRuta { get; set; }
        public virtual DbSet<HorasTrabEqPesadosTecnologicos> HorasTrabEqPesadosTecnologicos { get; set; }
        public virtual DbSet<InvFinalCombEqMes> InvFinalCombEqMes { get; set; }
        public virtual DbSet<ListaNegraEquipos> ListaNegraEquipos { get; set; }
        public virtual DbSet<LugarCarga> LugarCarga { get; set; }
        public virtual DbSet<LugarDescarga> LugarDescarga { get; set; }
        public virtual DbSet<LugarMttoFuera> LugarMttoFuera { get; set; }
        public virtual DbSet<Mantenimientos> Mantenimientos { get; set; }
        public virtual DbSet<MenuOpciones> MenuOpciones { get; set; }
        public virtual DbSet<MenuOpcionesUsuario> MenuOpcionesUsuario { get; set; }
        public virtual DbSet<Motores> Motores { get; set; }
        public virtual DbSet<MotoresComb> MotoresComb { get; set; }
        public virtual DbSet<MotoresNormasConsumo> MotoresNormasConsumo { get; set; }
        public virtual DbSet<MovTarjCombCaja> MovTarjCombCaja { get; set; }
        public virtual DbSet<Mtto_Fuera> Mtto_Fuera { get; set; }
        public virtual DbSet<MttoFuera_DetMO> MttoFuera_DetMO { get; set; }
        public virtual DbSet<MttoFuera_Materiales> MttoFuera_Materiales { get; set; }
        public virtual DbSet<MttoFuera_RotSistemas> MttoFuera_RotSistemas { get; set; }
        public virtual DbSet<MttoFuera_TI> MttoFuera_TI { get; set; }
        public virtual DbSet<MttoFuera_TRep> MttoFuera_TRep { get; set; }
        public virtual DbSet<mundo_Aceites> mundo_Aceites { get; set; }
        public virtual DbSet<mundo_Arrastres> mundo_Arrastres { get; set; }
        public virtual DbSet<mundo_Baterias> mundo_Baterias { get; set; }
        public virtual DbSet<mundo_Brigadas> mundo_Brigadas { get; set; }
        public virtual DbSet<mundo_Cabinas> mundo_Cabinas { get; set; }
        public virtual DbSet<mundo_Carrocerias> mundo_Carrocerias { get; set; }
        public virtual DbSet<mundo_CategoriasEquipos> mundo_CategoriasEquipos { get; set; }
        public virtual DbSet<mundo_CausasBajas> mundo_CausasBajas { get; set; }
        public virtual DbSet<mundo_CiclosMantenimiento> mundo_CiclosMantenimiento { get; set; }
        public virtual DbSet<mundo_Combustibles> mundo_Combustibles { get; set; }
        public virtual DbSet<mundo_Documentos> mundo_Documentos { get; set; }
        public virtual DbSet<mundo_Equipos> mundo_Equipos { get; set; }
        public virtual DbSet<mundo_Indicadores> mundo_Indicadores { get; set; }
        public virtual DbSet<mundo_Mantenimientos> mundo_Mantenimientos { get; set; }
        public virtual DbSet<mundo_MarcasBateria> mundo_MarcasBateria { get; set; }
        public virtual DbSet<mundo_MarcasEquipos> mundo_MarcasEquipos { get; set; }
        public virtual DbSet<mundo_MarcasMotores> mundo_MarcasMotores { get; set; }
        public virtual DbSet<mundo_MarcasNeumaticos> mundo_MarcasNeumaticos { get; set; }
        public virtual DbSet<mundo_motores> mundo_motores { get; set; }
        public virtual DbSet<mundo_neumaticos> mundo_neumaticos { get; set; }
        public virtual DbSet<mundo_Obreros> mundo_Obreros { get; set; }
        public virtual DbSet<mundo_Paises> mundo_Paises { get; set; }
        public virtual DbSet<mundo_Paralizaciones> mundo_Paralizaciones { get; set; }
        public virtual DbSet<mundo_ParqueoAutorizo> mundo_ParqueoAutorizo { get; set; }
        public virtual DbSet<mundo_PropositosEquipos> mundo_PropositosEquipos { get; set; }
        public virtual DbSet<mundo_PropositosGenerales> mundo_PropositosGenerales { get; set; }
        public virtual DbSet<mundo_RotSistemas> mundo_RotSistemas { get; set; }
        public virtual DbSet<mundo_ServAutoLOT> mundo_ServAutoLOT { get; set; }
        public virtual DbSet<mundo_Servicios> mundo_Servicios { get; set; }
        public virtual DbSet<mundo_SistemasAuto> mundo_SistemasAuto { get; set; }
        public virtual DbSet<mundo_Talleres> mundo_Talleres { get; set; }
        public virtual DbSet<mundo_TipoBombeo> mundo_TipoBombeo { get; set; }
        public virtual DbSet<mundo_TipoHR> mundo_TipoHR { get; set; }
        public virtual DbSet<mundo_Traccion> mundo_Traccion { get; set; }
        public virtual DbSet<mundo_Trafico> mundo_Trafico { get; set; }
        public virtual DbSet<mundo_Transmision> mundo_Transmision { get; set; }
        public virtual DbSet<Neumaticos> Neumaticos { get; set; }
        public virtual DbSet<NeumMotivoBaja> NeumMotivoBaja { get; set; }
        public virtual DbSet<NeumRepEq> NeumRepEq { get; set; }
        public virtual DbSet<OperacionesARealizar> OperacionesARealizar { get; set; }
        public virtual DbSet<OrdenesTrabajo> OrdenesTrabajo { get; set; }
        public virtual DbSet<OT_Terceros> OT_Terceros { get; set; }
        public virtual DbSet<OTServiciosPrestados> OTServiciosPrestados { get; set; }
        public virtual DbSet<OTServPrestDet> OTServPrestDet { get; set; }
        public virtual DbSet<ParametrosFijosApps> ParametrosFijosApps { get; set; }
        public virtual DbSet<PlanesMesIndicEq> PlanesMesIndicEq { get; set; }
        public virtual DbSet<ProductoTransportado> ProductoTransportado { get; set; }
        public virtual DbSet<RecaudaOmnibus> RecaudaOmnibus { get; set; }
        public virtual DbSet<RegistroParqueos> RegistroParqueos { get; set; }
        public virtual DbSet<ResumenHREquipos> ResumenHREquipos { get; set; }
        public virtual DbSet<rptCombHabKmsVehAdm> rptCombHabKmsVehAdm { get; set; }
        public virtual DbSet<Salidas_Almacenes> Salidas_Almacenes { get; set; }
        public virtual DbSet<SubmayorBonosPeaje> SubmayorBonosPeaje { get; set; }
        public virtual DbSet<SubmayorCombPagCargar> SubmayorCombPagCargar { get; set; }
        public virtual DbSet<SubmayorPeaje> SubmayorPeaje { get; set; }
        public virtual DbSet<SubmayorTarjetasExternas> SubmayorTarjetasExternas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TarifaKmsTransp> TarifaKmsTransp { get; set; }
        public virtual DbSet<TarjetasExternas> TarjetasExternas { get; set; }
        public virtual DbSet<TarjetasPeaje> TarjetasPeaje { get; set; }
        public virtual DbSet<TempariosMtto> TempariosMtto { get; set; }
        public virtual DbSet<TiposProdDensidad> TiposProdDensidad { get; set; }
        public virtual DbSet<TiposProductos> TiposProductos { get; set; }
        public virtual DbSet<Trayectoria> Trayectoria { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosTalleres> UsuariosTalleres { get; set; }
        public virtual DbSet<UsuariosTrafico> UsuariosTrafico { get; set; }
        public virtual DbSet<DetOT_TiempoReparacion> DetOT_TiempoReparacion { get; set; }
        public virtual DbSet<ExistProd_Taller> ExistProd_Taller { get; set; }
        public virtual DbSet<KmsArrastres> KmsArrastres { get; set; }
        public virtual DbSet<KmsNeumaticos> KmsNeumaticos { get; set; }
        public virtual DbSet<Registro> Registro { get; set; }
    
        [DbFunction("SitransEntities", "ft_CCostos")]
        public virtual IQueryable<ft_CCostos_Result> ft_CCostos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_CCostos_Result>("[SitransEntities].[ft_CCostos]()");
        }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        [DbFunction("SitransEntities", "ft_CapacidadEqTrabPeriodo")]
        public virtual IQueryable<ft_CapacidadEqTrabPeriodo_Result> ft_CapacidadEqTrabPeriodo(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_CapacidadEqTrabPeriodo_Result>("[SitransEntities].[ft_CapacidadEqTrabPeriodo](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        [DbFunction("SitransEntities", "ft_CapEqTrabPeriodoCargaSeca")]
        public virtual IQueryable<ft_CapEqTrabPeriodoCargaSeca_Result> ft_CapEqTrabPeriodoCargaSeca(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_CapEqTrabPeriodoCargaSeca_Result>("[SitransEntities].[ft_CapEqTrabPeriodoCargaSeca](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        [DbFunction("SitransEntities", "ft_CapEqTrabPeriodoFluidos")]
        public virtual IQueryable<ft_CapEqTrabPeriodoFluidos_Result> ft_CapEqTrabPeriodoFluidos(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_CapEqTrabPeriodoFluidos_Result>("[SitransEntities].[ft_CapEqTrabPeriodoFluidos](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        [DbFunction("SitransEntities", "ft_ConsumoEquiposPeriodo")]
        public virtual IQueryable<ft_ConsumoEquiposPeriodo_Result> ft_ConsumoEquiposPeriodo(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_ConsumoEquiposPeriodo_Result>("[SitransEntities].[ft_ConsumoEquiposPeriodo](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        [DbFunction("SitransEntities", "ft_DetalleHREqsPeriodo")]
        public virtual IQueryable<ft_DetalleHREqsPeriodo_Result> ft_DetalleHREqsPeriodo(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_DetalleHREqsPeriodo_Result>("[SitransEntities].[ft_DetalleHREqsPeriodo](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        [DbFunction("SitransEntities", "ft_EqEnListNegra")]
        public virtual IQueryable<ft_EqEnListNegra_Result> ft_EqEnListNegra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_EqEnListNegra_Result>("[SitransEntities].[ft_EqEnListNegra]()");
        }
    
        [DbFunction("SitransEntities", "ft_EqMttoAdelantar")]
        public virtual IQueryable<ft_EqMttoAdelantar_Result> ft_EqMttoAdelantar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_EqMttoAdelantar_Result>("[SitransEntities].[ft_EqMttoAdelantar]()");
        }
    
        [DbFunction("SitransEntities", "ft_EqMttoAtrasar")]
        public virtual IQueryable<ft_EqMttoAtrasar_Result> ft_EqMttoAtrasar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_EqMttoAtrasar_Result>("[SitransEntities].[ft_EqMttoAtrasar]()");
        }
    
        [DbFunction("SitransEntities", "ft_EqsBat")]
        public virtual IQueryable<ft_EqsBat_Result> ft_EqsBat(Nullable<bool> baja, string matricula, string noBat)
        {
            var bajaParameter = baja.HasValue ?
                new ObjectParameter("Baja", baja) :
                new ObjectParameter("Baja", typeof(bool));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var noBatParameter = noBat != null ?
                new ObjectParameter("NoBat", noBat) :
                new ObjectParameter("NoBat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_EqsBat_Result>("[SitransEntities].[ft_EqsBat](@Baja, @Matricula, @NoBat)", bajaParameter, matriculaParameter, noBatParameter);
        }
    
        [DbFunction("SitransEntities", "ft_EqsMotor")]
        public virtual IQueryable<ft_EqsMotor_Result> ft_EqsMotor(Nullable<bool> baja, string matricula, string noMotor)
        {
            var bajaParameter = baja.HasValue ?
                new ObjectParameter("Baja", baja) :
                new ObjectParameter("Baja", typeof(bool));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var noMotorParameter = noMotor != null ?
                new ObjectParameter("NoMotor", noMotor) :
                new ObjectParameter("NoMotor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_EqsMotor_Result>("[SitransEntities].[ft_EqsMotor](@Baja, @Matricula, @NoMotor)", bajaParameter, matriculaParameter, noMotorParameter);
        }
    
        [DbFunction("SitransEntities", "ft_EqsNeum")]
        public virtual IQueryable<ft_EqsNeum_Result> ft_EqsNeum(Nullable<bool> baja, string matricula, string noNeum)
        {
            var bajaParameter = baja.HasValue ?
                new ObjectParameter("Baja", baja) :
                new ObjectParameter("Baja", typeof(bool));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var noNeumParameter = noNeum != null ?
                new ObjectParameter("NoNeum", noNeum) :
                new ObjectParameter("NoNeum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_EqsNeum_Result>("[SitransEntities].[ft_EqsNeum](@Baja, @Matricula, @NoNeum)", bajaParameter, matriculaParameter, noNeumParameter);
        }
    
        [DbFunction("SitransEntities", "ft_EqsProp")]
        public virtual IQueryable<string> ft_EqsProp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[SitransEntities].[ft_EqsProp]()");
        }
    
        [DbFunction("SitransEntities", "ft_EqsPropCS")]
        public virtual IQueryable<string> ft_EqsPropCS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[SitransEntities].[ft_EqsPropCS]()");
        }
    
        [DbFunction("SitransEntities", "ft_EqsPropTCOE")]
        public virtual IQueryable<string> ft_EqsPropTCOE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[SitransEntities].[ft_EqsPropTCOE]()");
        }
    
        [DbFunction("SitransEntities", "ft_EqsTrabFecha")]
        public virtual IQueryable<ft_EqsTrabFecha_Result> ft_EqsTrabFecha(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_EqsTrabFecha_Result>("[SitransEntities].[ft_EqsTrabFecha](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        [DbFunction("SitransEntities", "ft_ListEqNoCalT2")]
        public virtual IQueryable<string> ft_ListEqNoCalT2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[SitransEntities].[ft_ListEqNoCalT2]()");
        }
    
        [DbFunction("SitransEntities", "ft_ListEqsTrabDiaCS")]
        public virtual IQueryable<ft_ListEqsTrabDiaCS_Result> ft_ListEqsTrabDiaCS(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_ListEqsTrabDiaCS_Result>("[SitransEntities].[ft_ListEqsTrabDiaCS](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        [DbFunction("SitransEntities", "ft_ListEqsTrabDiaTCOE")]
        public virtual IQueryable<ft_ListEqsTrabDiaTCOE_Result> ft_ListEqsTrabDiaTCOE(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_ListEqsTrabDiaTCOE_Result>("[SitransEntities].[ft_ListEqsTrabDiaTCOE](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        [DbFunction("SitransEntities", "ft_ListEqTodos")]
        public virtual IQueryable<ft_ListEqTodos_Result> ft_ListEqTodos(string matricula, string numOperacional, Nullable<short> paisID, Nullable<short> marcaID, Nullable<short> modeloID, string lineaID, Nullable<decimal> propEqID, string codCCosto, string propiedad, Nullable<bool> baja)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var numOperacionalParameter = numOperacional != null ?
                new ObjectParameter("NumOperacional", numOperacional) :
                new ObjectParameter("NumOperacional", typeof(string));
    
            var paisIDParameter = paisID.HasValue ?
                new ObjectParameter("PaisID", paisID) :
                new ObjectParameter("PaisID", typeof(short));
    
            var marcaIDParameter = marcaID.HasValue ?
                new ObjectParameter("MarcaID", marcaID) :
                new ObjectParameter("MarcaID", typeof(short));
    
            var modeloIDParameter = modeloID.HasValue ?
                new ObjectParameter("ModeloID", modeloID) :
                new ObjectParameter("ModeloID", typeof(short));
    
            var lineaIDParameter = lineaID != null ?
                new ObjectParameter("LineaID", lineaID) :
                new ObjectParameter("LineaID", typeof(string));
    
            var propEqIDParameter = propEqID.HasValue ?
                new ObjectParameter("PropEqID", propEqID) :
                new ObjectParameter("PropEqID", typeof(decimal));
    
            var codCCostoParameter = codCCosto != null ?
                new ObjectParameter("CodCCosto", codCCosto) :
                new ObjectParameter("CodCCosto", typeof(string));
    
            var propiedadParameter = propiedad != null ?
                new ObjectParameter("Propiedad", propiedad) :
                new ObjectParameter("Propiedad", typeof(string));
    
            var bajaParameter = baja.HasValue ?
                new ObjectParameter("Baja", baja) :
                new ObjectParameter("Baja", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_ListEqTodos_Result>("[SitransEntities].[ft_ListEqTodos](@Matricula, @NumOperacional, @PaisID, @MarcaID, @ModeloID, @LineaID, @PropEqID, @CodCCosto, @Propiedad, @Baja)", matriculaParameter, numOperacionalParameter, paisIDParameter, marcaIDParameter, modeloIDParameter, lineaIDParameter, propEqIDParameter, codCCostoParameter, propiedadParameter, bajaParameter);
        }
    
        [DbFunction("SitransEntities", "ft_ListIndicadores")]
        public virtual IQueryable<ft_ListIndicadores_Result> ft_ListIndicadores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_ListIndicadores_Result>("[SitransEntities].[ft_ListIndicadores]()");
        }
    
        [DbFunction("SitransEntities", "ft_ListMotivoBajaBat")]
        public virtual IQueryable<ft_ListMotivoBajaBat_Result> ft_ListMotivoBajaBat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_ListMotivoBajaBat_Result>("[SitransEntities].[ft_ListMotivoBajaBat]()");
        }
    
        [DbFunction("SitransEntities", "ft_ListMotivoBajaNeum")]
        public virtual IQueryable<ft_ListMotivoBajaNeum_Result> ft_ListMotivoBajaNeum()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_ListMotivoBajaNeum_Result>("[SitransEntities].[ft_ListMotivoBajaNeum]()");
        }
    
        [DbFunction("SitransEntities", "ft_MttoRealizadosEq")]
        public virtual IQueryable<ft_MttoRealizadosEq_Result> ft_MttoRealizadosEq(string matricula)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_MttoRealizadosEq_Result>("[SitransEntities].[ft_MttoRealizadosEq](@Matricula)", matriculaParameter);
        }
    
        [DbFunction("SitransEntities", "ft_PlanesEqIndYear")]
        public virtual IQueryable<ft_PlanesEqIndYear_Result> ft_PlanesEqIndYear(string año, Nullable<byte> indId)
        {
            var añoParameter = año != null ?
                new ObjectParameter("Año", año) :
                new ObjectParameter("Año", typeof(string));
    
            var indIdParameter = indId.HasValue ?
                new ObjectParameter("IndId", indId) :
                new ObjectParameter("IndId", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_PlanesEqIndYear_Result>("[SitransEntities].[ft_PlanesEqIndYear](@Año, @IndId)", añoParameter, indIdParameter);
        }
    
        [DbFunction("SitransEntities", "ft_SubmayorBonosPeajeCC")]
        public virtual IQueryable<ft_SubmayorBonosPeajeCC_Result> ft_SubmayorBonosPeajeCC(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, Nullable<int> dirID)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var dirIDParameter = dirID.HasValue ?
                new ObjectParameter("DirID", dirID) :
                new ObjectParameter("DirID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_SubmayorBonosPeajeCC_Result>("[SitransEntities].[ft_SubmayorBonosPeajeCC](@FechaIni, @FechaFin, @DirID)", fechaIniParameter, fechaFinParameter, dirIDParameter);
        }
    
        [DbFunction("SitransEntities", "ft_SubmayorTarjetasComb")]
        public virtual IQueryable<ft_SubmayorTarjetasComb_Result> ft_SubmayorTarjetasComb(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, Nullable<int> combID)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var combIDParameter = combID.HasValue ?
                new ObjectParameter("CombID", combID) :
                new ObjectParameter("CombID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_SubmayorTarjetasComb_Result>("[SitransEntities].[ft_SubmayorTarjetasComb](@FechaIni, @FechaFin, @CombID)", fechaIniParameter, fechaFinParameter, combIDParameter);
        }
    
        [DbFunction("SitransEntities", "ft_SubmayorTarjetasPeaje")]
        public virtual IQueryable<ft_SubmayorTarjetasPeaje_Result> ft_SubmayorTarjetasPeaje(Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin)
        {
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ft_SubmayorTarjetasPeaje_Result>("[SitransEntities].[ft_SubmayorTarjetasPeaje](@FechaIni, @FechaFin)", fechaIniParameter, fechaFinParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    }
}
