//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmayorBonosPeaje
    {
        public int ccosto_id { get; set; }
        public string eq_NumOperacional { get; set; }
        public System.DateTime ste_Fecha { get; set; }
        public int ImporteEntrega { get; set; }
        public int ImporteLiq { get; set; }
        public int Saldo { get; set; }
        public string Observ { get; set; }
    
        public virtual CentrosCostos CentrosCostos { get; set; }
        public virtual Equipos Equipos { get; set; }
    }
}
