//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetasExternas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TarjetasExternas()
        {
            this.ConsCombMotBT = new HashSet<ConsCombMotBT>();
            this.MovTarjCombCaja = new HashSet<MovTarjCombCaja>();
            this.SubmayorTarjetasExternas = new HashSet<SubmayorTarjetasExternas>();
        }
    
        public string te_No { get; set; }
        public string eq_NumOperacional { get; set; }
        public string mcomb_Id { get; set; }
        public short te_Cuota { get; set; }
        public int ccosto_id { get; set; }
        public string te_Responsable { get; set; }
        public string te_Estado { get; set; }
        public System.DateTime te_FechaCaduca { get; set; }
        public string te_TipoMoneda { get; set; }
        public string te_Observ { get; set; }
    
        public virtual CentrosCostos CentrosCostos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsCombMotBT> ConsCombMotBT { get; set; }
        public virtual Equipos Equipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovTarjCombCaja> MovTarjCombCaja { get; set; }
        public virtual mundo_Combustibles mundo_Combustibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmayorTarjetasExternas> SubmayorTarjetasExternas { get; set; }
    }
}
