//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetasPeaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TarjetasPeaje()
        {
            this.SubmayorPeaje = new HashSet<SubmayorPeaje>();
        }
    
        public string te_No { get; set; }
        public int ccosto_id { get; set; }
        public string te_Responsable { get; set; }
        public bool te_NoActivo { get; set; }
        public System.DateTime te_FechaCaduca { get; set; }
        public string te_Pin { get; set; }
        public string te_Observ { get; set; }
    
        public virtual CentrosCostos CentrosCostos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmayorPeaje> SubmayorPeaje { get; set; }
    }
}
