//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempariosMtto
    {
        public int TempID { get; set; }
        public string Comb { get; set; }
        public byte msa_Id { get; set; }
        public string mmant_Id { get; set; }
        public int IDOper { get; set; }
        public byte Horas { get; set; }
        public byte Min { get; set; }
    
        public virtual mundo_Mantenimientos mundo_Mantenimientos { get; set; }
        public virtual mundo_SistemasAuto mundo_SistemasAuto { get; set; }
    }
}
