//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trayectoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trayectoria()
        {
            this.DetallesHojaRuta = new HashSet<DetallesHojaRuta>();
        }
    
        public int Trayectoria_ID { get; set; }
        public int ldesc_ID { get; set; }
        public string Trayectoria_Nombre { get; set; }
        public string Trayectoria_Descrip { get; set; }
        public byte Trayectoria_Kms { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesHojaRuta> DetallesHojaRuta { get; set; }
    }
}
