//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sitrans
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.AdelantarMttoMotor = new HashSet<AdelantarMttoMotor>();
            this.AtrasarMttoMotor = new HashSet<AtrasarMttoMotor>();
            this.ListaNegraEquipos = new HashSet<ListaNegraEquipos>();
            this.MenuOpcionesUsuario = new HashSet<MenuOpcionesUsuario>();
            this.CentrosCostos = new HashSet<CentrosCostos>();
            this.mundo_Indicadores = new HashSet<mundo_Indicadores>();
        }
    
        public string Login { get; set; }
        public string Nombre { get; set; }
        public string Pass { get; set; }
        public string Tipo { get; set; }
        public bool Inactivo { get; set; }
        public Nullable<System.DateTime> FechaCaduca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdelantarMttoMotor> AdelantarMttoMotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtrasarMttoMotor> AtrasarMttoMotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaNegraEquipos> ListaNegraEquipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuOpcionesUsuario> MenuOpcionesUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentrosCostos> CentrosCostos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mundo_Indicadores> mundo_Indicadores { get; set; }
    }
}
