//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ajustes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ajustes()
        {
            this.Detalle_Ajustes = new HashSet<Detalle_Ajustes>();
        }
    
        public int Ajuste_Id { get; set; }
        public int Ajuste_Doc { get; set; }
        public System.DateTime Ajuste_fecha { get; set; }
        public string Ajuste_Estado { get; set; }
        public string Ajuste_Comentarios { get; set; }
        public byte ConcepAjuste_Id { get; set; }
        public string Almacen_Id { get; set; }
        public Nullable<int> Prelacion { get; set; }
    
        public virtual Conceptos_Ajustes Conceptos_Ajustes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Ajustes> Detalle_Ajustes { get; set; }
    }
}
