//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacenes()
        {
            this.Detalle_Recepcion = new HashSet<Detalle_Recepcion>();
            this.Devoluciones = new HashSet<Devoluciones>();
            this.Operadoras_Almacen = new HashSet<Operadoras_Almacen>();
            this.Productos_Almacen = new HashSet<Productos_Almacen>();
            this.Transferencias = new HashSet<Transferencias>();
            this.Transferencias1 = new HashSet<Transferencias>();
        }
    
        public string Almacen_Id { get; set; }
        public string Almacen_Descrip { get; set; }
        public Nullable<int> Almacen_Tranferencias { get; set; }
        public Nullable<int> Almacen_Ajustes { get; set; }
        public Nullable<int> Almacen_Reclamacion { get; set; }
        public Nullable<int> Almacen_Recepcion { get; set; }
        public Nullable<int> Almacen_ValSal { get; set; }
        public Nullable<int> Almacen_ValDev { get; set; }
        public Nullable<bool> Almacen_EsOcioso { get; set; }
        public Nullable<int> Almacen_PreFactura { get; set; }
        public Nullable<int> Almacen_Prelacion { get; set; }
        public Nullable<int> Almacen_Prelacion_ante { get; set; }
        public Nullable<System.DateTime> Almacen_Fsiscont { get; set; }
        public Nullable<int> Almacen_Oent { get; set; }
        public Nullable<int> Almacen_Osal { get; set; }
        public bool Almacen_SeExporta { get; set; }
        public Nullable<int> Almacen_Tde { get; set; }
        public Nullable<int> Almacen_Tds { get; set; }
        public Nullable<int> Almacen_Ept { get; set; }
        public Nullable<int> Almacen_Transfent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Recepcion> Detalle_Recepcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devoluciones> Devoluciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operadoras_Almacen> Operadoras_Almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos_Almacen> Productos_Almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transferencias> Transferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transferencias> Transferencias1 { get; set; }
    }
}
