//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaciones
    {
        public string Login { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> Prodalm_id { get; set; }
        public string Ctaccosto { get; set; }
        public string Operacion { get; set; }
    }
}
