//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTORI
    {
        public string USER_NAME { get; set; }
        public string COD_APLI { get; set; }
        public string COD_PER { get; set; }
        public string USER_ORA { get; set; }
        public string PASS_ORA { get; set; }
        public Nullable<System.DateTime> ULT_ACCESO { get; set; }
        public string MODIFICADO { get; set; }
    
        public virtual CATALOGO CATALOGO { get; set; }
        public virtual PERFILES PERFILES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
