//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciclo_Reapro
    {
        public Nullable<int> mproducto_id { get; set; }
        public Nullable<int> ano { get; set; }
        public string Um { get; set; }
        public Nullable<decimal> Norma { get; set; }
        public Nullable<decimal> Consumo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public int Ciclo_Id { get; set; }
    }
}
