//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciloted
    {
        public string clave_op { get; set; }
        public string cod_alm { get; set; }
        public string no_doc { get; set; }
        public string cod_prod { get; set; }
        public Nullable<decimal> cant_ent { get; set; }
        public Nullable<decimal> cant_alm { get; set; }
        public string cod_almr { get; set; }
        public string cond_fac { get; set; }
        public string emp_sum { get; set; }
        public Nullable<System.DateTime> f_doc { get; set; }
        public Nullable<decimal> imp_fact { get; set; }
        public string orden_pre { get; set; }
        public string seccion { get; set; }
        public string estante { get; set; }
        public string casilla { get; set; }
        public string ccosto { get; set; }
        public Nullable<decimal> imp_mn { get; set; }
        public Nullable<decimal> imp_md { get; set; }
        public string um { get; set; }
        public Nullable<int> notrans { get; set; }
        public int ciloted_id { get; set; }
    }
}
