//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciproda
    {
        public string Cod_prod { get; set; }
        public string um_alm { get; set; }
        public decimal Precio { get; set; }
        public string Descipcion { get; set; }
    }
}
