//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciprodwk2
    {
        public string cod_prod { get; set; }
        public string um_alm { get; set; }
        public decimal precio { get; set; }
        public string desc_prod { get; set; }
        public Nullable<decimal> Prec_mn { get; set; }
        public Nullable<decimal> Prec_md { get; set; }
    }
}
