//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_RecAlm_Temporal
    {
        public int DetRecAlm_Id { get; set; }
        public int DetRecep_Id { get; set; }
        public int ProdAlm_Id { get; set; }
        public Nullable<decimal> DetRecalm_PrecioUSD { get; set; }
        public Nullable<decimal> DetRecalm_PrecioMNC { get; set; }
        public Nullable<decimal> DetRecalm_Cantidad { get; set; }
        public Nullable<decimal> DetRecalm_Existencia { get; set; }
        public Nullable<decimal> DetRecalm_ImporteMNC { get; set; }
        public Nullable<decimal> DetRecalm_ImporteUSD { get; set; }
    }
}
