//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Prerecepcion_Nuevo
    {
        public int Prerec_Id { get; set; }
        public int Detalle_id { get; set; }
        public string Codprod { get; set; }
        public string Prerec_Um { get; set; }
        public decimal Prerec_Precio { get; set; }
        public decimal Prerec_Cantidad { get; set; }
        public decimal Prerec_Conteo { get; set; }
    }
}
