//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_RecAlm
    {
        public int DetRecAlm_Id { get; set; }
        public int DetRecep_Id { get; set; }
        public int ProdAlm_Id { get; set; }
        public decimal DetRecAlm_PrecioUsd { get; set; }
        public decimal DetRecAlm_PrecioMnc { get; set; }
        public decimal DetRecAlm_Cantidad { get; set; }
        public decimal DetRecAlm_Existencia { get; set; }
        public decimal DetRecAlm_importemnc { get; set; }
        public decimal DetRecAlm_importeusd { get; set; }
    }
}
