//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Ajustes
    {
        public int Ajuste_Id { get; set; }
        public int mProducto_Id { get; set; }
        public decimal DetAjus_Cantidad { get; set; }
        public decimal DetAjus_Existencia { get; set; }
        public decimal DetAjus_Tarjeta { get; set; }
    
        public virtual Ajustes Ajustes { get; set; }
    }
}
