//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetDevoluciones
    {
        public int Dev_Id { get; set; }
        public int ProdAlm_Id { get; set; }
        public decimal detDev_Cantidad { get; set; }
        public decimal detDev_ExistAntes { get; set; }
        public decimal detDev_ExistTarjeta { get; set; }
    }
}
