//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistProd_CCosto
    {
        public int ProdAlm_Id { get; set; }
        public string CtaCCosto { get; set; }
        public decimal DProdCC_Cantidad { get; set; }
        public decimal DProdCC_CantPred { get; set; }
        public Nullable<System.DateTime> DprodCC_FechaAsig { get; set; }
    }
}
