//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entradas_Almacen
    {
        public int EntAlm_ir { get; set; }
        public int mProducto_id { get; set; }
        public string Almacen_id { get; set; }
        public System.DateTime EntAlm_fecha { get; set; }
        public string Ccosto_id { get; set; }
        public string Ent { get; set; }
    }
}
