//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class especif
    {
        public string cod_esp { get; set; }
        public string cod_gen { get; set; }
        public string cod_sge { get; set; }
        public string descrip { get; set; }
    }
}
