//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado_Recepcion
    {
        public int prerec_id { get; set; }
        public bool ERecepcion_Calcula { get; set; }
        public bool ERecepcion_Distribuir { get; set; }
        public bool ERecepcion_Reclama { get; set; }
        public bool ERecepcion_Anulada { get; set; }
        public bool ERecepcion_Aplicada { get; set; }
    }
}
