//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONES_SUBC
    {
        public string SUBCONJ { get; set; }
        public int INDICE { get; set; }
        public string APLICACION { get; set; }
    
        public virtual SUBCONJUNTOS SUBCONJUNTOS { get; set; }
    }
}
