//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitesProductos
    {
        public int mProducto_id { get; set; }
        public Nullable<float> LimiteP_maximo { get; set; }
        public Nullable<float> LimiteP_minimo { get; set; }
        public Nullable<float> LimiteP_ptoReorden { get; set; }
    }
}
