//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento_Productos
    {
        public int Mov_NoDoc { get; set; }
        public int ProdAlm_Id { get; set; }
        public System.DateTime Mov_Fecha { get; set; }
        public string TipoMov_Id { get; set; }
        public decimal Mov_Cantidad { get; set; }
        public decimal Mov_Precio { get; set; }
        public decimal Mov_Existencia { get; set; }
        public int Opera_Id { get; set; }
        public int Mov_Id { get; set; }
        public Nullable<decimal> Mov_PrecioMnc { get; set; }
        public Nullable<decimal> Mov_PrecioUsd { get; set; }
        public string Mov_ccosto { get; set; }
        public string Mov_Ot { get; set; }
        public string Mov_HostName { get; set; }
    
        public virtual Operadores Operadores { get; set; }
        public virtual Tipos_Movimientos Tipos_Movimientos { get; set; }
    }
}
