//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mundo_Productos
    {
        public int mProducto_Id { get; set; }
        public int Especifico_Id { get; set; }
        public string mProducto_Surtido { get; set; }
        public string mProducto_Descrip { get; set; }
        public decimal mProducto_Precio { get; set; }
        public string mProducto_Status { get; set; }
        public System.DateTime mProducto_FechaAlta { get; set; }
        public Nullable<decimal> mProducto_PrecioMn { get; set; }
        public Nullable<decimal> mProducto_PrecioMd { get; set; }
        public string mProducto_ElemtoMn { get; set; }
        public string mProducto_ElemtoMd { get; set; }
        public Nullable<decimal> CIcuIdCuenta { get; set; }
        public Nullable<bool> mProducto_Sensible { get; set; }
    }
}
