//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mundo_Intervalo
    {
        public Nullable<int> ProdAlm_Id { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<System.DateTime> FEntrada { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> PrecioCUC { get; set; }
        public Nullable<decimal> PrecioCUP { get; set; }
        public Nullable<decimal> ImpCUC { get; set; }
        public Nullable<decimal> ImpCUP { get; set; }
        public int Inter_Id { get; set; }
    }
}
