//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mundo_Importe_Inicio
    {
        public string Almacen_Id { get; set; }
        public Nullable<System.DateTime> MInicio_FechaFecha { get; set; }
        public Nullable<decimal> MInicio_ImporteCUP { get; set; }
        public Nullable<decimal> MInicio_ImporteCUC { get; set; }
        public int MInicio_Id { get; set; }
    }
}
