//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreciosSiscont
    {
        public string cod_prod { get; set; }
        public string cta_inv { get; set; }
        public string scta_inv { get; set; }
        public string des_prod { get; set; }
        public string um_alm { get; set; }
        public decimal precio { get; set; }
        public decimal prec_mn { get; set; }
        public decimal prec_md { get; set; }
        public string cod_aux { get; set; }
        public string subel_mn { get; set; }
        public string subel_md { get; set; }
    }
}
