//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class procenco
    {
        public decimal prerec { get; set; }
        public string codprod { get; set; }
        public string codcencos { get; set; }
        public decimal cantidad { get; set; }
        public decimal cantpred { get; set; }
    }
}
