//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcion_anulada
    {
        public int Prerec_Id { get; set; }
        public int IR_No { get; set; }
        public string Almacen_Id { get; set; }
        public System.DateTime IR_Fecha { get; set; }
        public System.DateTime RAnu_Fecha { get; set; }
        public int Opera_id { get; set; }
    
        public virtual Prerecepcion Prerecepcion { get; set; }
    }
}
