//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelProdTipos
    {
        public int mProducto_Id { get; set; }
        public int TipoProd_Id { get; set; }
        public Nullable<int> Actividad_id { get; set; }
    
        public virtual Tipos_Productos Tipos_Productos { get; set; }
    }
}
