//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalAlm_Factura
    {
        public int SalAlm_Id { get; set; }
        public int Fact_Id { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
