//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salidas_Temp
    {
        public string almacen_id { get; set; }
        public Nullable<int> SalAlm_NoVs { get; set; }
        public System.DateTime FechaDesp { get; set; }
        public int ProdAlm_Id { get; set; }
        public Nullable<decimal> SalAlm_Cantidad { get; set; }
    }
}
