//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBCONJUNTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBCONJUNTOS()
        {
            this.FUNCIONES_SUBC = new HashSet<FUNCIONES_SUBC>();
        }
    
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string APLICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNCIONES_SUBC> FUNCIONES_SUBC { get; set; }
        public virtual CATALOGO CATALOGO { get; set; }
    }
}
