//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGenericosProductos
    {
        public string Generico_Id { get; set; }
        public string SubGProd_Codigo { get; set; }
        public string SubGProd_Descrip { get; set; }
        public int SubGProd_Id { get; set; }
    
        public virtual GenericoProductos GenericoProductos { get; set; }
    }
}
