//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Winatm
{
    using System;
    using System.Collections.Generic;
    
    public partial class uno
    {
        public string ccosto_Id { get; set; }
        public string cliente_id { get; set; }
        public int mProducto_Id { get; set; }
        public decimal cantdev { get; set; }
        public Nullable<int> tipoprod_id { get; set; }
        public Nullable<int> salalm_id { get; set; }
        public Nullable<int> prodalm_id { get; set; }
        public Nullable<decimal> prodalm_existencia { get; set; }
        public string Cliente { get; set; }
        public string status { get; set; }
    }
}
