//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_Evaluaciones
    {
        public Nullable<int> Eval_id { get; set; }
        public int Indic_id { get; set; }
        public string ccosto_id { get; set; }
        public int Eval_año { get; set; }
        public int Eval_mes { get; set; }
        public Nullable<int> Eval_puntos { get; set; }
    
        public virtual AM_Indicadores AM_Indicadores { get; set; }
    }
}
