//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_Indicadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AM_Indicadores()
        {
            this.AM_CriteriosIndic = new HashSet<AM_CriteriosIndic>();
            this.AM_Evaluaciones = new HashSet<AM_Evaluaciones>();
        }
    
        public int Indic_id { get; set; }
        public string Indic_desc { get; set; }
        public string Alcance_id { get; set; }
        public string Indic_regula { get; set; }
    
        public virtual AM_Alcance AM_Alcance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AM_CriteriosIndic> AM_CriteriosIndic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AM_Evaluaciones> AM_Evaluaciones { get; set; }
    }
}
