//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_PresPlanRealSubElto
    {
        public string ccosto_id { get; set; }
        public int subelCodigo { get; set; }
        public int PP_año { get; set; }
        public Nullable<decimal> PP_enp { get; set; }
        public Nullable<decimal> PP_fep { get; set; }
        public Nullable<decimal> PP_map { get; set; }
        public Nullable<decimal> PP_abp { get; set; }
        public Nullable<decimal> PP_myp { get; set; }
        public Nullable<decimal> PP_jup { get; set; }
        public Nullable<decimal> PP_jlp { get; set; }
        public Nullable<decimal> PP_agp { get; set; }
        public Nullable<decimal> PP_sep { get; set; }
        public Nullable<decimal> PP_ocp { get; set; }
        public Nullable<decimal> PP_nop { get; set; }
        public Nullable<decimal> PP_dip { get; set; }
        public Nullable<decimal> PP_enr { get; set; }
        public Nullable<decimal> PP_fer { get; set; }
        public Nullable<decimal> PP_mar { get; set; }
        public Nullable<decimal> PP_abr { get; set; }
        public Nullable<decimal> PP_myr { get; set; }
        public Nullable<decimal> PP_jur { get; set; }
        public Nullable<decimal> PP_jlr { get; set; }
        public Nullable<decimal> PP_agr { get; set; }
        public Nullable<decimal> PP_ser { get; set; }
        public Nullable<decimal> PP_ocr { get; set; }
        public Nullable<decimal> PP_nor { get; set; }
        public Nullable<decimal> PP_dir { get; set; }
    
        public virtual SCGSUBELEMENTO SCGSUBELEMENTO { get; set; }
    }
}
