//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCostos
    {
        public string Subd_Id { get; set; }
        public string Cuenta_Id { get; set; }
        public string CCosto_Id { get; set; }
        public string CCosto_Descrip { get; set; }
        public Nullable<int> JefeCC_Id { get; set; }
        public bool CCosto_Activado { get; set; }
        public bool CCosto_PlanOp { get; set; }
        public string Subelem_id { get; set; }
        public Nullable<int> ccosto_idN { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual JefeCC JefeCC { get; set; }
        public virtual Subdirecciones Subdirecciones { get; set; }
    }
}
