//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class MbasAcum
    {
        public string c_costo { get; set; }
        public string d_costo { get; set; }
        public string c_dpto { get; set; }
        public string d_dpto { get; set; }
        public string c_inve { get; set; }
        public string cnmb { get; set; }
        public string d_mbas { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> a_repa { get; set; }
        public Nullable<decimal> a_repo { get; set; }
        public Nullable<System.DateTime> f_alta { get; set; }
        public string subel { get; set; }
        public string SubElem_Descrip { get; set; }
    }
}
