//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ot
    {
        public int nuot { get; set; }
        public string cliente { get; set; }
        public Nullable<System.DateTime> fechaSolic { get; set; }
        public Nullable<decimal> costo_obrero { get; set; }
        public Nullable<decimal> costo_producto { get; set; }
        public Nullable<decimal> costo_equipo { get; set; }
        public Nullable<decimal> costo_total { get; set; }
        public Nullable<System.DateTime> fechainicio { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> No_Equipo { get; set; }
        public string ccosto { get; set; }
        public string clienteN { get; set; }
        public Nullable<int> ccostoN { get; set; }
    
        public virtual OT_Tipo OT_Tipo { get; set; }
    }
}
