//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_EquipoFactServ
    {
        public int efs_id { get; set; }
        public int efs_NoFact { get; set; }
        public int efs_NoEquipo { get; set; }
    
        public virtual OT_FacturaServicio OT_FacturaServicio { get; set; }
    }
}
