//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_ProdValesSal
    {
        public int ProdAlm_Id { get; set; }
        public int NoVs { get; set; }
        public Nullable<decimal> CantDesp { get; set; }
        public Nullable<decimal> CantDisp { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
