//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_PiezaFactServ
    {
        public int pfs_NoFact { get; set; }
        public string pfs_Descripcion { get; set; }
        public Nullable<int> pfs_Cantidad { get; set; }
        public Nullable<int> pfs_CantDisp { get; set; }
        public int mp_id { get; set; }
        public int pfs_id { get; set; }
    }
}
