//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_ServiciosP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OT_ServiciosP()
        {
            this.OT_Pieza = new HashSet<OT_Pieza>();
        }
    
        public int nuotf { get; set; }
        public string clientef { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> No_Equipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT_Pieza> OT_Pieza { get; set; }
        public virtual OT_TrabajoFS OT_TrabajoFS { get; set; }
    }
}
