//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_Servicios
    {
        public int nuots { get; set; }
        public string clientes { get; set; }
        public Nullable<System.DateTime> fechas { get; set; }
        public Nullable<int> No_Equipo { get; set; }
    }
}
