//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanOperativo
    {
        public string SubElem_Id { get; set; }
        public string Ccosto_Id { get; set; }
        public Nullable<decimal> PlanOper_ValorPlan { get; set; }
        public Nullable<decimal> PlanOper_ValorReal { get; set; }
        public Nullable<decimal> PlanOper_ValorPredesp { get; set; }
    }
}
