//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestoGastos
    {
        public string CCosto_Id { get; set; }
        public string subelem_id { get; set; }
        public int año { get; set; }
        public Nullable<decimal> enp { get; set; }
        public Nullable<decimal> fep { get; set; }
        public Nullable<decimal> map { get; set; }
        public Nullable<decimal> abp { get; set; }
        public Nullable<decimal> myp { get; set; }
        public Nullable<decimal> jup { get; set; }
        public Nullable<decimal> jlp { get; set; }
        public Nullable<decimal> agp { get; set; }
        public Nullable<decimal> sep { get; set; }
        public Nullable<decimal> ocp { get; set; }
        public Nullable<decimal> nop { get; set; }
        public Nullable<decimal> dip { get; set; }
        public Nullable<decimal> enr { get; set; }
        public Nullable<decimal> fer { get; set; }
        public Nullable<decimal> mar { get; set; }
        public Nullable<decimal> abr { get; set; }
        public Nullable<decimal> myr { get; set; }
        public Nullable<decimal> jur { get; set; }
        public Nullable<decimal> jlr { get; set; }
        public Nullable<decimal> agr { get; set; }
        public Nullable<decimal> ser { get; set; }
        public Nullable<decimal> ocr { get; set; }
        public Nullable<decimal> nor { get; set; }
        public Nullable<decimal> dir { get; set; }
        public Nullable<decimal> enpo { get; set; }
        public Nullable<decimal> fepo { get; set; }
        public Nullable<decimal> mapo { get; set; }
        public Nullable<decimal> abpo { get; set; }
        public Nullable<decimal> mypo { get; set; }
        public Nullable<decimal> jupo { get; set; }
        public Nullable<decimal> jlpo { get; set; }
        public Nullable<decimal> agpo { get; set; }
        public Nullable<decimal> sepo { get; set; }
        public Nullable<decimal> ocpo { get; set; }
        public Nullable<decimal> nopo { get; set; }
        public Nullable<decimal> dipo { get; set; }
        public Nullable<int> ccosto_idN { get; set; }
    }
}
