//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int prodalm_id { get; set; }
        public string prod_descrip { get; set; }
        public string um { get; set; }
        public Nullable<decimal> pu { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> insumo { get; set; }
        public string codprod { get; set; }
        public Nullable<decimal> precioMn { get; set; }
        public Nullable<decimal> precioMd { get; set; }
        public string ElementoMn { get; set; }
        public string ElementoMd { get; set; }
        public string prod_activ { get; set; }
    }
}
