//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SicencoEntities : DbContext
    {
        public SicencoEntities()
            : base("name=SicencoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AM_Alcance> AM_Alcance { get; set; }
        public virtual DbSet<AM_CriteriosIndic> AM_CriteriosIndic { get; set; }
        public virtual DbSet<AM_Evaluaciones> AM_Evaluaciones { get; set; }
        public virtual DbSet<AM_Indicadores> AM_Indicadores { get; set; }
        public virtual DbSet<AM_PresPlanRealSubElto> AM_PresPlanRealSubElto { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<CCostos> CCostos { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        //public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<Elementos> Elementos { get; set; }
        public virtual DbSet<ElemMnDi> ElemMnDi { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<JefeCC> JefeCC { get; set; }
        public virtual DbSet<obreros> obreros { get; set; }
        public virtual DbSet<Ot> Ot { get; set; }
        public virtual DbSet<OT_Clientes> OT_Clientes { get; set; }
        public virtual DbSet<OT_Comp731> OT_Comp731 { get; set; }
        public virtual DbSet<Ot_Comprobantes> Ot_Comprobantes { get; set; }
        public virtual DbSet<OT_EquipoFactServ> OT_EquipoFactServ { get; set; }
        public virtual DbSet<OT_FacturaServicio> OT_FacturaServicio { get; set; }
        public virtual DbSet<Ot_Insumos> Ot_Insumos { get; set; }
        public virtual DbSet<OT_Pieza> OT_Pieza { get; set; }
        public virtual DbSet<OT_PiezaFactServ> OT_PiezaFactServ { get; set; }
        public virtual DbSet<OT_PiezaFSAlmacen> OT_PiezaFSAlmacen { get; set; }
        public virtual DbSet<OT_ProdValesSal> OT_ProdValesSal { get; set; }
        public virtual DbSet<OT_Servicios> OT_Servicios { get; set; }
        public virtual DbSet<OT_ServiciosP> OT_ServiciosP { get; set; }
        public virtual DbSet<OT_Tipo> OT_Tipo { get; set; }
        public virtual DbSet<OT_TrabajoFS> OT_TrabajoFS { get; set; }
        public virtual DbSet<PlanOperativo> PlanOperativo { get; set; }
        public virtual DbSet<PresPlan_SubEl> PresPlan_SubEl { get; set; }
        public virtual DbSet<Presupuesto_Producto> Presupuesto_Producto { get; set; }
        public virtual DbSet<Presupuesto_SubElemento> Presupuesto_SubElemento { get; set; }
        public virtual DbSet<PresupuestoCcostos> PresupuestoCcostos { get; set; }
        public virtual DbSet<PresupuestoEmpresa> PresupuestoEmpresa { get; set; }
        public virtual DbSet<PresupuestoGastos> PresupuestoGastos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<SCGSUBELEMENTO> SCGSUBELEMENTO { get; set; }
        public virtual DbSet<Solicitud> Solicitud { get; set; }
        public virtual DbSet<Subdirecciones> Subdirecciones { get; set; }
        public virtual DbSet<SubElementos> SubElementos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TasaDepMB> TasaDepMB { get; set; }
        public virtual DbSet<Trabajos> Trabajos { get; set; }
        public virtual DbSet<OT_Cta731> OT_Cta731 { get; set; }
        public virtual DbSet<OT_MundoPiezasFact> OT_MundoPiezasFact { get; set; }
        public virtual DbSet<Ot_Usuarios> Ot_Usuarios { get; set; }
        public virtual DbSet<Producto_Solicitud> Producto_Solicitud { get; set; }
        public virtual DbSet<SCCSUBMAYORCOSTO> SCCSUBMAYORCOSTO { get; set; }
        public virtual DbSet<TControl> TControl { get; set; }
        public virtual DbSet<tpresupuesto> tpresupuesto { get; set; }
        public virtual DbSet<CCActivos> CCActivos { get; set; }
        public virtual DbSet<MbasAcum> MbasAcum { get; set; }
        public virtual DbSet<pressiscont> pressiscont { get; set; }
        public virtual DbSet<solicitudes> solicitudes { get; set; }
        public virtual DbSet<ver_Subdir_Ccostos> ver_Subdir_Ccostos { get; set; }
        public virtual DbSet<VIEW1> VIEW1 { get; set; }
        public virtual DbSet<VIEW2> VIEW2 { get; set; }
        public virtual DbSet<VIEW3> VIEW3 { get; set; }
        public virtual DbSet<VIEW4> VIEW4 { get; set; }
        public virtual DbSet<VIEW5> VIEW5 { get; set; }
        public virtual DbSet<VIEW6> VIEW6 { get; set; }
        public virtual DbSet<VIEW7> VIEW7 { get; set; }
        public virtual DbSet<VIEW8> VIEW8 { get; set; }
        public virtual DbSet<VIEW9> VIEW9 { get; set; }
    
        public virtual int Borrar_PedidosInsumos(Nullable<int> prodAlm_Id, string ctaCCosto)
        {
            var prodAlm_IdParameter = prodAlm_Id.HasValue ?
                new ObjectParameter("ProdAlm_Id", prodAlm_Id) :
                new ObjectParameter("ProdAlm_Id", typeof(int));
    
            var ctaCCostoParameter = ctaCCosto != null ?
                new ObjectParameter("CtaCCosto", ctaCCosto) :
                new ObjectParameter("CtaCCosto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Borrar_PedidosInsumos", prodAlm_IdParameter, ctaCCostoParameter);
        }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual ObjectResult<Esta_CCostoConstr_Result> Esta_CCostoConstr(string ccosto_id)
        {
            var ccosto_idParameter = ccosto_id != null ?
                new ObjectParameter("Ccosto_id", ccosto_id) :
                new ObjectParameter("Ccosto_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Esta_CCostoConstr_Result>("Esta_CCostoConstr", ccosto_idParameter);
        }
    
        public virtual ObjectResult<OT_InventariosMedBasicos_Web__Result> OT_InventariosMedBasicos_Web_(string noInve)
        {
            var noInveParameter = noInve != null ?
                new ObjectParameter("NoInve", noInve) :
                new ObjectParameter("NoInve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OT_InventariosMedBasicos_Web__Result>("OT_InventariosMedBasicos_Web_", noInveParameter);
        }
    
        public virtual ObjectResult<Report_PrecioProductoSiscont_Result> Report_PrecioProductoSiscont(string almacen_id, string descrip, string reporte)
        {
            var almacen_idParameter = almacen_id != null ?
                new ObjectParameter("almacen_id", almacen_id) :
                new ObjectParameter("almacen_id", typeof(string));
    
            var descripParameter = descrip != null ?
                new ObjectParameter("descrip", descrip) :
                new ObjectParameter("descrip", typeof(string));
    
            var reporteParameter = reporte != null ?
                new ObjectParameter("Reporte", reporte) :
                new ObjectParameter("Reporte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_PrecioProductoSiscont_Result>("Report_PrecioProductoSiscont", almacen_idParameter, descripParameter, reporteParameter);
        }
    
        public virtual ObjectResult<Report_PresGastosSubEl_Result> Report_PresGastosSubEl(Nullable<int> gnAño, string ccosto_id, string subd_id, string tipo)
        {
            var gnAñoParameter = gnAño.HasValue ?
                new ObjectParameter("gnAño", gnAño) :
                new ObjectParameter("gnAño", typeof(int));
    
            var ccosto_idParameter = ccosto_id != null ?
                new ObjectParameter("ccosto_id", ccosto_id) :
                new ObjectParameter("ccosto_id", typeof(string));
    
            var subd_idParameter = subd_id != null ?
                new ObjectParameter("subd_id", subd_id) :
                new ObjectParameter("subd_id", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_PresGastosSubEl_Result>("Report_PresGastosSubEl", gnAñoParameter, ccosto_idParameter, subd_idParameter, tipoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sql_Ccostos_Result> sql_Ccostos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_Ccostos_Result>("sql_Ccostos");
        }
    
        public virtual ObjectResult<sql_CcostosDeLaSubd_Result> sql_CcostosDeLaSubd(string subd_Id)
        {
            var subd_IdParameter = subd_Id != null ?
                new ObjectParameter("Subd_Id", subd_Id) :
                new ObjectParameter("Subd_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_CcostosDeLaSubd_Result>("sql_CcostosDeLaSubd", subd_IdParameter);
        }
    
        public virtual ObjectResult<sql_CcostosDelUsuario_Result> sql_CcostosDelUsuario(Nullable<int> jefeCc_Id)
        {
            var jefeCc_IdParameter = jefeCc_Id.HasValue ?
                new ObjectParameter("JefeCc_Id", jefeCc_Id) :
                new ObjectParameter("JefeCc_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_CcostosDelUsuario_Result>("sql_CcostosDelUsuario", jefeCc_IdParameter);
        }
    
        public virtual ObjectResult<sql_CcostosDelUsuRepo_Result> sql_CcostosDelUsuRepo(Nullable<int> jefeCc_Id)
        {
            var jefeCc_IdParameter = jefeCc_Id.HasValue ?
                new ObjectParameter("JefeCc_Id", jefeCc_Id) :
                new ObjectParameter("JefeCc_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_CcostosDelUsuRepo_Result>("sql_CcostosDelUsuRepo", jefeCc_IdParameter);
        }
    
        public virtual ObjectResult<sql_CcostosDSubd_Result> sql_CcostosDSubd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_CcostosDSubd_Result>("sql_CcostosDSubd");
        }
    
        public virtual ObjectResult<sql_CcostosTodos_Result> sql_CcostosTodos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_CcostosTodos_Result>("sql_CcostosTodos");
        }
    
        public virtual ObjectResult<sql_DatosDelCCosto_Result> sql_DatosDelCCosto(string ccosto_Id)
        {
            var ccosto_IdParameter = ccosto_Id != null ?
                new ObjectParameter("Ccosto_Id", ccosto_Id) :
                new ObjectParameter("Ccosto_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_DatosDelCCosto_Result>("sql_DatosDelCCosto", ccosto_IdParameter);
        }
    
        public virtual int sql_DistribucionProductos(string codprod, string almacen_id)
        {
            var codprodParameter = codprod != null ?
                new ObjectParameter("codprod", codprod) :
                new ObjectParameter("codprod", typeof(string));
    
            var almacen_idParameter = almacen_id != null ?
                new ObjectParameter("almacen_id", almacen_id) :
                new ObjectParameter("almacen_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sql_DistribucionProductos", codprodParameter, almacen_idParameter);
        }
    
        public virtual ObjectResult<sql_PresupProductos_Result> sql_PresupProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_PresupProductos_Result>("sql_PresupProductos");
        }
    
        public virtual ObjectResult<sql_PresupuestoDelCCosto_Result> sql_PresupuestoDelCCosto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_PresupuestoDelCCosto_Result>("sql_PresupuestoDelCCosto");
        }
    
        public virtual int sql_ProductosBalancDeLCCosto(Nullable<int> mProducto_Id, string ccosto_Id, string almacen_id)
        {
            var mProducto_IdParameter = mProducto_Id.HasValue ?
                new ObjectParameter("mProducto_Id", mProducto_Id) :
                new ObjectParameter("mProducto_Id", typeof(int));
    
            var ccosto_IdParameter = ccosto_Id != null ?
                new ObjectParameter("Ccosto_Id", ccosto_Id) :
                new ObjectParameter("Ccosto_Id", typeof(string));
    
            var almacen_idParameter = almacen_id != null ?
                new ObjectParameter("almacen_id", almacen_id) :
                new ObjectParameter("almacen_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sql_ProductosBalancDeLCCosto", mProducto_IdParameter, ccosto_IdParameter, almacen_idParameter);
        }
    
        public virtual int sql_ProductosDelCCosto(string ccosto_Id)
        {
            var ccosto_IdParameter = ccosto_Id != null ?
                new ObjectParameter("Ccosto_Id", ccosto_Id) :
                new ObjectParameter("Ccosto_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sql_ProductosDelCCosto", ccosto_IdParameter);
        }
    
        public virtual int sql_ProductosNormadosDelCcosto(string ccosto_Id)
        {
            var ccosto_IdParameter = ccosto_Id != null ?
                new ObjectParameter("Ccosto_Id", ccosto_Id) :
                new ObjectParameter("Ccosto_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sql_ProductosNormadosDelCcosto", ccosto_IdParameter);
        }
    
        public virtual ObjectResult<sql_Subdirecciones_Result> sql_Subdirecciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sql_Subdirecciones_Result>("sql_Subdirecciones");
        }
    
        public virtual ObjectResult<WSBuscar_CCosto_porDescrip_Result> WSBuscar_CCosto_porDescrip(string cCosto_Descrip)
        {
            var cCosto_DescripParameter = cCosto_Descrip != null ?
                new ObjectParameter("CCosto_Descrip", cCosto_Descrip) :
                new ObjectParameter("CCosto_Descrip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WSBuscar_CCosto_porDescrip_Result>("WSBuscar_CCosto_porDescrip", cCosto_DescripParameter);
        }
    
        public virtual ObjectResult<WSBuscar_CCosto_porId_Result> WSBuscar_CCosto_porId(string cCosto_id)
        {
            var cCosto_idParameter = cCosto_id != null ?
                new ObjectParameter("CCosto_id", cCosto_id) :
                new ObjectParameter("CCosto_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WSBuscar_CCosto_porId_Result>("WSBuscar_CCosto_porId", cCosto_idParameter);
        }
    
        [DbFunction("SicencoEntities", "AM_Evaluaciones2")]
        public virtual IQueryable<AM_Evaluaciones2_Result> AM_Evaluaciones2(string ccosto_id, Nullable<int> año, Nullable<int> mes)
        {
            var ccosto_idParameter = ccosto_id != null ?
                new ObjectParameter("ccosto_id", ccosto_id) :
                new ObjectParameter("ccosto_id", typeof(string));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("Año", año) :
                new ObjectParameter("Año", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AM_Evaluaciones2_Result>("[SicencoEntities].[AM_Evaluaciones2](@ccosto_id, @Año, @Mes)", ccosto_idParameter, añoParameter, mesParameter);
        }
    
        [DbFunction("SicencoEntities", "AM_Evaluaciones4")]
        public virtual IQueryable<AM_Evaluaciones4_Result> AM_Evaluaciones4(string ccosto_id, Nullable<int> año, Nullable<int> mes)
        {
            var ccosto_idParameter = ccosto_id != null ?
                new ObjectParameter("ccosto_id", ccosto_id) :
                new ObjectParameter("ccosto_id", typeof(string));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("Año", año) :
                new ObjectParameter("Año", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AM_Evaluaciones4_Result>("[SicencoEntities].[AM_Evaluaciones4](@ccosto_id, @Año, @Mes)", ccosto_idParameter, añoParameter, mesParameter);
        }
    
        [DbFunction("SicencoEntities", "AM_SubElementos")]
        public virtual IQueryable<AM_SubElementos_Result> AM_SubElementos(string ccosto_id, Nullable<int> año)
        {
            var ccosto_idParameter = ccosto_id != null ?
                new ObjectParameter("ccosto_id", ccosto_id) :
                new ObjectParameter("ccosto_id", typeof(string));
    
            var añoParameter = año.HasValue ?
                new ObjectParameter("Año", año) :
                new ObjectParameter("Año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AM_SubElementos_Result>("[SicencoEntities].[AM_SubElementos](@ccosto_id, @Año)", ccosto_idParameter, añoParameter);
        }
    
        [DbFunction("SicencoEntities", "Jubilacion")]
        public virtual IQueryable<Jubilacion_Result> Jubilacion(string ccosto_id)
        {
            var ccosto_idParameter = ccosto_id != null ?
                new ObjectParameter("ccosto_id", ccosto_id) :
                new ObjectParameter("ccosto_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Jubilacion_Result>("[SicencoEntities].[Jubilacion](@ccosto_id)", ccosto_idParameter);
        }
    }
}
