//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes
    {
        public decimal numsolic_id { get; set; }
        public string almacen_id { get; set; }
        public string ccosto_id { get; set; }
        public System.DateTime FechaSolic { get; set; }
        public Nullable<System.DateTime> FechaDesp { get; set; }
        public string Estado { get; set; }
        public string Cliente_Id { get; set; }
        public Nullable<int> SalAlm_NoVS { get; set; }
        public Nullable<decimal> NuOt { get; set; }
        public string chapa { get; set; }
        public string mProducto_Descrip { get; set; }
        public string Expr1 { get; set; }
        public string JefeCC_Descrip { get; set; }
    }
}
