//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Producto_Solicitud = new HashSet<Producto_Solicitud>();
        }
    
        public decimal numsolic_id { get; set; }
        public string almacen_id { get; set; }
        public string ccosto_id { get; set; }
        public System.DateTime FechaSolic { get; set; }
        public Nullable<System.DateTime> FechaDesp { get; set; }
        public string Estado { get; set; }
        public string Cliente_Id { get; set; }
        public Nullable<int> SalAlm_NoVS { get; set; }
        public Nullable<decimal> NuOt { get; set; }
        public string chapa { get; set; }
        public string SGM { get; set; }
        public Nullable<int> ccosto_idN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Solicitud> Producto_Solicitud { get; set; }
    }
}
