//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpresupuesto
    {
        public string codcencos { get; set; }
        public string codelem { get; set; }
        public decimal valplan { get; set; }
        public decimal valreal { get; set; }
    }
}
