//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajos
    {
        public string trabajo_id { get; set; }
        public string Trabajo_descrip { get; set; }
        public Nullable<decimal> tarifa { get; set; }
        public string Trabajo_Actividad { get; set; }
    }
}
