//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW4
    {
        public string Cuenta_Id { get; set; }
        public string CCosto_Id { get; set; }
        public string CCosto_Descrip { get; set; }
        public Nullable<int> JefeCC_Id { get; set; }
        public string JefeCC_Descrip { get; set; }
        public string JefeCC_CtaUser { get; set; }
    }
}
