//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suite.Models.Sicenco
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW8
    {
        public decimal numsolic_id { get; set; }
        public System.DateTime FechaSolic { get; set; }
        public string ccosto_id { get; set; }
        public int mproducto_Id { get; set; }
        public decimal Expr1 { get; set; }
        public string Estado { get; set; }
        public decimal Cantidad { get; set; }
    }
}
